import { createContext, useContext, useState, useCallback } from 'react'

const translations = {
  en: {
    // ── Nav ──────────────────────────────────────────────────────────────────
    dashboard: 'Dashboard',
    students: 'Students',
    teachers: 'Teachers',
    classes: 'Classes',
    subjects: 'Subjects',
    gradebook: 'Gradebook',
    attendance: 'Attendance',
    noticeboard: 'Notice Board',
    resources: 'Resources',
    auditlog: 'Audit Log',
    registration: 'Registration',
    regrade: 'Regrade',
    userlookup: 'User Lookup',
    account: 'Account',
    logout: 'Logout',
    myGrades: 'My Grades',
    myAttendance: 'Attendance',
    notices: 'Notices',
    myChildren: 'My Children',
    reportCards: 'Report Cards',
    // ── Admin grouped nav labels ─────────────────────────────────────────────
    navRegistration: 'Registration',
    navAcademics: 'Academics',
    navManagement: 'Management & Tools',
    studentRegistration: 'Student Registration',
    teacherRegistration: 'Teacher Registration',

    // ── Login ────────────────────────────────────────────────────────────────
    signIn: 'Sign in',
    signInSubtitle: 'Use your username or email address.',
    usernameEmail: 'Username / Email',
    password: 'Password',
    signingIn: 'Signing in…',
    troubleSignIn: 'Trouble signing in? Contact the school office.',
    forDirectors: 'For Directors',
    forTeachers: 'For Teachers',
    forStudents: 'For Students',
    forParents: 'For Parents',
    manageSchool: 'Manage the whole school',
    gradesAttendance: 'Grades, attendance, materials',
    viewResults: 'View results, get materials',
    trackChild: "Track your child's progress",

    // ── Common actions ───────────────────────────────────────────────────────
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    searching: 'Searching…',
    loading: 'Loading…',
    noData: 'No data found.',
    required: 'Required',
    confirm: 'Confirm',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    register: 'Register',
    submit: 'Submit',
    update: 'Update',
    remove: 'Remove',
    view: 'View',
    hide: 'Hide',
    upload: 'Upload',
    uploading: 'Uploading…',
    download: 'Download',
    downloading: 'Downloading…',
    approve: 'Approve',
    reject: 'Reject',
    review: 'Review',
    unlink: 'Unlink',
    all: 'All',
    prev: 'Prev',
    page: 'Page',
    of: 'of',
    by: 'By',
    total: 'Total',
    assigned: 'Assigned',
    pending: 'pending',
    active: 'Active',
    disabled: 'Disabled',
    copied: 'Copied!',
    copyToClipboard: 'Copy to Clipboard',
    changeFile: 'Change file',
    uploadFile: 'Upload file',
    saveChanges: 'Save Changes',

    // ── Page titles ──────────────────────────────────────────────────────────
    studentsPage: 'Students',
    teachersPage: 'Teachers',
    classesPage: 'Classes',
    subjectsPage: 'Subjects',
    attendancePage: 'Attendance',
    noticeBoardPage: 'Notice Board',
    resourcesPage: 'Resources',
    auditLogPage: 'Audit Log',
    myGradesPage: 'My Grades',
    myAttendancePage: 'My Attendance',
    accountPage: 'My Account',
    myChildrenPage: 'My Children',
    userLookupPageTitle: 'User Lookup',

    // ── Attendance page ──────────────────────────────────────────────────────
    attendanceSubtitleAdmin: 'Mark daily attendance by class',
    attendanceSubtitleTeacher: 'Mark attendance for your homeroom class',
    selectClass: 'Select class',
    dateLabel: 'Date',
    dayLabel: 'Day',
    markAllPresent: 'Mark All Present',
    markAllAbsent: 'Mark All Absent',
    allMarkedAs: 'All marked as',
    present: 'Present',
    absent: 'Absent',
    absentOther: 'Absent/Other',
    late: 'Late',
    excused: 'Excused',
    attendanceRate: 'Attendance Rate',
    noHomeroomAssigned: 'You are not assigned as a homeroom teacher to any class.',
    notHomeroomTeacher: '⚠️ You are not assigned as a homeroom teacher to any class. Contact the director.',
    selectClassToMark: 'Select a class to mark attendance.',
    noStudentsInSection: 'No students in this section.',
    student: 'Student',
    statusLabel: 'Status',
    actions: 'Actions',
    failedToLoadClasses: 'Failed to load classes',
    failedToLoadAttendance: 'Failed to load attendance',
    failedToSaveAttendance: 'Failed to save attendance',

    // ── My Attendance page ───────────────────────────────────────────────────
    noClassAssigned: 'No class assigned',
    daysLabel: 'days',
    attendanceLowWarning: 'Your attendance is below 75%. Please speak with your teacher or guardian.',
    noAttendanceRecords: 'No attendance records yet.',
    noteLabel: 'Note',
    markedByLabel: 'Marked By',
    studentProfileNotSetup: 'Your student profile is not set up yet. Contact the administrator.',

    // ── Notice Board ─────────────────────────────────────────────────────────
    titleLabel: 'Title',
    bodyLabel: 'Body',
    audienceLabel: 'Audience',
    priorityLabel: 'Priority',
    pinNotice: 'Pin this notice to the top',
    pinned: 'Pinned',
    noticesCount: 'notices',
    noNotices: 'No notices yet.',
    postNotice: 'Post Notice',
    editNotice: 'Edit Notice',
    noticePosted: 'Notice posted',
    noticeUpdated: 'Notice updated',
    noticeDeleted: 'Notice deleted',
    deleteNoticeConfirm: 'Delete notice',
    failedToLoadNotices: 'Failed to load notices',

    // ── Resources ────────────────────────────────────────────────────────────
    descriptionLabel: 'Description',
    subjectLabel: 'Subject',
    fileLabel: 'File',
    maxFileSize: 'Max 25 MB.',
    noResources: 'No resources yet.',
    uploadResource: 'Upload Resource',
    resourceUploaded: 'Resource uploaded',
    resourceDeleted: 'Resource deleted',
    uploadFailed: 'Upload failed',
    downloadFailed: 'Download failed',
    deleteResourceConfirm: 'Delete resource',
    failedToLoadResources: 'Failed to load resources',
    choosefile: 'Please choose a file',
    files: 'files',

    // ── Subjects page ────────────────────────────────────────────────────────
    subjectName: 'Subject Name',
    codeLabel: 'Code',
    applicableGrades: 'Applicable Grades',
    noSubjectsFound: 'No subjects found.',
    subjectsDefined: 'subjects defined',
    addSubject: 'Add Subject',
    editSubject: 'Edit Subject',
    subjectAdded: 'Subject added',
    subjectUpdated: 'Subject updated',
    subjectDeleted: 'Subject deleted',
    deleteSubjectConfirm: 'Delete subject',
    failedToLoadSubjects: 'Failed to load subjects',

    // ── Classes page ─────────────────────────────────────────────────────────
    grade: 'Grade',
    section: 'Section',
    academicYear: 'Academic Year',
    homeroomTeacher: 'Homeroom Teacher',
    maxCapacity: 'Max Capacity',
    stream: 'Stream',
    naturalScience: 'Natural Science',
    socialScience: 'Social Science',
    selectStream: 'Select stream',
    requiredForGrade1112: 'required for Grade 11–12',
    noneLabel: 'None',
    homeroomNote: 'The homeroom teacher is the only teacher who can mark attendance for this class.',
    subjectAssignments: 'Subject Assignments',
    gradeCurriculum: 'Grade Curriculum',
    endTerm: 'End Term',
    endAcademicYearTerm: 'End Academic Year Term',
    autoAssignStudents: 'Auto-Assign Students',
    sectionsConfigured: 'sections configured',
    addClass: 'Add Class',
    editClass: 'Edit Class',
    classCreated: 'Class created – curriculum auto-applied from grade template',
    classUpdated: 'Class updated',
    classDeleted: 'Class deleted',
    deleteClassConfirm: 'Delete',
    noClassesYet: 'No classes yet. Add your first class to get started.',
    failedToLoadAssignments: 'Failed to load assignments',
    teacherAssigned: 'Teacher assigned',
    failedToAssignTeacher: 'Failed to assign teacher',
    subjectsNeedTeacher: 'subject(s) still need a teacher assigned',
    noSubjectsAssigned: 'No subjects assigned yet.',
    curriculumAutoApplied: 'Curriculum is applied automatically when the class is created.',
    assignTeacher: 'Assign teacher',
    noCurriculumForGrade: 'No curriculum defined for Grade',
    subjectsAppliedFromCurriculum: 'subject(s) applied from Grade',
    failedToApplyCurriculum: 'Failed to apply curriculum',
    failedToLoadCurriculum: 'Failed to load curriculum',
    curriculumDescription: 'Define which subjects are automatically assigned when a new class is created.',
    selectStreamFirst: 'Select a stream first',
    subjectAddedToCurriculum: 'Subject added to curriculum',
    subjectRemovedFromCurriculum: 'Subject removed from curriculum',
    addSubjectToCurriculum: 'Add subject to curriculum',
    noSubjectsInCurriculum: 'No subjects in Grade',
    selectStreamToView: 'Select a stream to view and edit the Grade',
    curriculum: 'curriculum.',
    failedToAdd: 'Failed to add',
    failedToRemove: 'Failed to remove',
    endOfYearAction: 'End of Academic Year Action',
    endTermNote1: 'All subject-teacher assignments for the year will be archived',
    endTermNote2: 'All students will be unassigned from their current classes',
    endTermNote3: 'Class records, subjects, and assignment history are preserved',
    endTermNote4: 'You will need to reassign students to their new classes manually',
    termEndedSuccess: 'Term ended successfully',
    failedToEndTerm: 'Failed to end term',
    termEndedFor: 'Term ended for',
    subjectAssignmentsArchived: 'subject assignments archived',
    studentsUnassigned: 'students unassigned from classes',
    academicYearToEnd: 'Academic Year to End',
    processing: 'Processing…',

    // ── Audit Log ────────────────────────────────────────────────────────────
    auditEvents: 'events',
    systemActivityTrail: 'System activity trail',
    allEntityTypes: 'All entity types',
    noAuditEvents: 'No audit events yet.',
    whenLabel: 'When',
    actorLabel: 'Actor',
    actionLabel: 'Action',
    entityLabel: 'Entity',
    detailsLabel: 'Details',
    failedToLoadAuditLog: 'Failed to load audit logs',

    // ── Account page ─────────────────────────────────────────────────────────
    accountSubtitle: 'View your profile and manage your password',
    profileLabel: 'Profile',
    roleLabel: 'Role',
    nameLabel: 'Full name',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPasswordLabel: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    min6chars: 'min 6 characters',
    updatePassword: 'Update Password',
    passwordChanged: 'Password changed successfully',
    failedToChangePassword: 'Failed to change password',
    passwordTooShort: 'Password must be at least 6 characters',
    passwordsDoNotMatch: 'New passwords do not match',
    passwordAcceptable: 'Acceptable',
    passwordStrong: 'Strong',

    // ── My Grades page ───────────────────────────────────────────────────────
    semester: 'Semester',
    year: 'Year',
    average: 'Average',
    subjectsLabel: 'Subjects',
    overallAverage: 'Overall Average',
    noGradesForSemester: 'No grades recorded for Semester',
    scoreLabel: 'Score',
    gradeLabel: 'Grade',
    commentLabel: 'Comment',
    failedToLoadStudent: 'Failed to load student data',
    midExam: 'Mid Exam',
    finalExam: 'Final Exam',
    assignment: 'Assignment',
    testQuiz: 'Test/Quiz',
    saveMarks: 'Save Marks',
    marksLocked: 'Marks are locked. Request regrade permission from the director to edit.',
    requestRegrade: 'Request Regrade',

    // ── Parent Children page ─────────────────────────────────────────────────
    linkedChildren: 'linked',
    linkAChild: 'Link a Child',
    linkChild: 'Link Child',
    linking: 'Linking…',
    childLinked: 'Child linked',
    linkFailed: 'Could not link – check the Student UID',
    childUnlinked: 'Child unlinked',
    unlinkFailed: 'Unlink failed',
    confirmUnlink: 'Confirm Unlink',
    unlinkConfirm: 'Unlink',
    noChildrenLinked: 'No children linked yet. Use the Student UID given to you by the school office.',
    studentUidLabel: 'Student UID',
    studentUidHint: "Get this ID from the school office or your child's enrollment letter.",
    failedToLoadChildren: 'Failed to load linked children',
    relationship: 'Relationship',

    // ── Parent Report Card page ──────────────────────────────────────────────
    reportCardsSubtitle: "View your child's academic performance",
    childLabel: 'Child',
    teacherCommentLabel: 'Teacher Comment',
    loadingReportCard: 'Loading report card…',
    noChildrenForReportCard: 'No children linked yet. Go to My Children to link your child.',

    // ── User Lookup page ─────────────────────────────────────────────────────
    userLookupSubtitle: 'Find any user to view their username or reset their password.',
    searchByNameUsernameEmail: 'Search by name, username or email',
    noUsersFound: 'No users found for',
    viewResetPassword: 'View / Reset Password',
    credentialsFor: 'Credentials –',
    passwordResetSuccess: 'Password reset successfully',
    resetFailed: 'Reset failed',
    passwordResetShareNote: 'Password reset. Share these credentials with the user – they must change it on next login.',
    enterNewPasswordForUser: 'Enter new password for this user',
    passwordResetTip: 'Tip: use something like Arerti@2026 and tell the user to change it.',
    resetting: 'Resetting…',
    resetPassword: 'Reset Password',
    searchFailed: 'Search failed',

    // ── Regrade Requests page ────────────────────────────────────────────────
    regradeSubtitle: 'Review and approve homeroom teacher requests to edit locked marks',
    noRequests: 'No',
    teacherLabel: 'Teacher',
    classLabel: 'Class',
    reasonLabel: 'Reason',
    noteToTeacher: 'Note to Teacher (optional)',
    addNoteForTeacher: 'Add a note for the teacher',
    regradeApproved: 'Regrade request approved',
    regradeRejected: 'Regrade request rejected',
    resolveFailed: 'Failed to resolve',
    reviewRegradeRequest: 'Review Regrade Request',
    failedToLoadRegrade: 'Failed to load regrade requests',

    // ── Teachers page ────────────────────────────────────────────────────────
    staffMembers: 'staff members',
    addTeacher: 'Add Teacher',
    registerTeacher: 'Register Teacher',
    editTeacher: 'Edit Teacher',
    teacherRegistered: 'Teacher registered',
    teacherUpdated: 'Teacher updated',
    teacherDeleted: 'Teacher deleted',
    deleteTeacherConfirm: 'Delete teacher',
    noTeachersFound: 'No teachers found.',
    failedToLoadTeachers: 'Failed to load teachers',
    teacherRegisteredSuccess: 'Teacher registered successfully. Share these credentials.',
    passwordShownOnce: 'Password shown once only. Teacher must change on first login.',
    teacherCredentials: 'Teacher Login Credentials',
    personalInfo: 'Personal Information',
    professionalInfo: 'Professional Information',
    documentsSection: 'Documents',
    credentialsAutoGenerated: 'Username and password will be auto-generated and shown after saving.',
    selectLabel: 'Select',
    firstName: 'First Name',
    fatherName: "Father's Name",
    grandfatherName: "Grandfather's Name",
    gender: 'Gender',
    dateOfBirth: 'Date of Birth',
    email: 'Email',
    region: 'Region',
    city: 'City / Woreda',
    kebele: 'Kebele',
    houseNo: 'House No.',
    phone: 'Phone',
    qualification: 'Qualification',
    specialization: 'Specialization',
    hireDate: 'Hire Date',
    teacherPhoto: 'Teacher Photo',
    qualificationCert: 'Qualification Certificate',
    idDocument: 'ID / Birth Certificate',
    photoLabel: 'Photo',
    uploaded: 'uploaded',
    failedToUpload: 'Failed to upload',

    // ── Students page ────────────────────────────────────────────────────────
    addStudent: 'Add Student',
    enrolled: 'enrolled',
    fullName: 'Full Name',
    username: 'Username',
    guardianPhone: 'Parent Phone',
    enrollmentYear: 'Enrollment Year',
    classSection: 'Class / Section',
    male: 'Male',
    female: 'Female',
    unassigned: 'Unassigned',
    leaveBlankToKeep: 'leave blank to keep',
    parentName: 'Parent / Guardian Full Name',
    parentPhone: 'Phone Number',

    // ── Registration page ────────────────────────────────────────────────────
    registrationSubtitle: 'Manage registration windows and teacher assignments',
    registrationOpened: 'Registration Opened',
    registrationClosed: 'Registration Closed',
    openRegistration: 'Open Registration Window',
    openRegistrationWindow: 'Open Registration Window',
    closeRegistration: 'Close Registration',
    postponeRegistration: 'Postpone Registration',
    newEndDate: 'New End Date & Time',
    postponeReason: 'Reason for Postponement',
    postponeReasonPlaceholder: 'e.g. Extended by 3 days for late applicants',
    assignedTeachers: 'Assigned Teachers',
    allowedGrades: 'Allowed Grades',
    selectTeacher: 'Select teacher',
    startDateTime: 'Start Date & Time',
    endDateTime: 'End Date & Time',
    optionalNote: 'Optional note',
    opening: 'Opening…',
    assigning: 'Assigning…',
    postponing: 'Postponing…',
    activeWindows: 'Active Windows',
    pastWindows: 'Past Windows',
    noWindowsYet: 'No registration windows yet. Open one to start student enrollment.',
    closeRegistrationWindow: 'Close Registration Window',
    closeWindowWarning: 'Closing this window will immediately prevent teachers from registering students. This cannot be undone.',
    closeWindowConfirm: 'Close window for',
    newEndDateRequired: 'New end date and time is required',
    registrationPostponed: 'Registration window postponed',
    failedToPostpone: 'Failed to postpone',
    currentEnd: 'Current end',
    newEndMustBeLater: 'New end must be later than current end.',
    registrationWindowOpened: 'Registration window opened',
    registrationWindowClosed: 'Registration window closed',
    failedToOpenWindow: 'Failed to open window',
    failedToClose: 'Failed to close',
    assignmentRemoved: 'Assignment removed',
    failedToLoad: 'Failed to load',
    failedToLoadEnrollments: 'Failed to load enrollments',
    selectAtLeastOneGrade: 'Select at least one grade',
    failedToAssign: 'Failed to assign',
    liveNow: 'Live now',
    postponed: 'Postponed',
    openedBy: 'Opened by',
    enrollments: 'Enrollments',
    enrollmentAudit: 'Enrollment Audit',
    noEnrollments: 'No enrollments yet',
    studentsRegistered: 'student(s) registered',
    endDateRequired: 'End date and time is required',
    autoAssignStudentsTitle: 'Auto-Assign Students to Sections',
    autoAssignTitle: 'Auto-Assign Students to Sections',
    autoAssignDescription: 'Students are sorted by their previous grade\'s performance score, then distributed evenly across sections using round-robin so every section gets a balanced mix.',
    autoAssignFailed: 'Auto-assign failed',
    autoAssignWarning: 'Make sure sections for Grade',
    goToClasses: 'Go to Classes to create sections first.',
    runAutoAssign: 'Run Auto-Assign',
    perSection: 'Per section',
    studentsCount: 'students',

    // ── Grade Submission Date (formerly Grade Entry Window) ──────────────────
    gradeEntryWindow: 'Grade Submission Date',
    openGradeEntry: 'Open Submission Period',
    closeGradeEntry: 'Close Submission Period',
    postponeGradeEntry: 'Extend Submission Period',
    gradeEntryOpen: 'Grade submission is open',
    gradeEntryClosed: 'Grade submission is closed. Wait for the director to open it.',

    // ── Dashboard ────────────────────────────────────────────────────────────
    welcomeAdmin: 'Welcome',
    directorOverview: "Director's overview of the school system",
    manageStudents: 'Manage',
    manageTeachers: 'Manage',
    manageClasses: 'Manage',
    manageNotices: 'Manage',
    studentRegistrationCard: 'Student Registration',
    studentRegistrationDesc: 'Open windows, assign teachers, enroll students',
    gradebookCard: 'Gradebook',
    gradebookDesc: 'Enter & review grades',
    attendanceCard: 'Attendance',
    attendanceDesc: 'Mark & review attendance',
    subjectsCard: 'Subjects',
    subjectsDesc: 'Manage subjects & grades',
    regradeCard: 'Regrade Requests',
    regradeDesc: 'Review mark correction requests',
    resourcesCard: 'Resources',
    resourcesDesc: 'Upload & manage study materials',
    auditLogCard: 'Audit Log',
    auditLogDesc: 'Review system activity',
    gradeEntryCard: 'Grade Submission',
    gradeEntryDesc: 'Open grade submission period after final exams',
    userLookupCard: 'User Lookup',
    userLookupDesc: 'Find username, reset forgotten password',
    teacherWorkspace: 'Teacher workspace',
    helloTeacher: 'Hello',
    enterGrades: 'Enter & manage grades',
    markAttendance: 'Mark daily attendance',
    viewNotices: 'View notice board',
    yourSchoolSnapshot: 'Your school snapshot',
    trackChildProgress: "Track your child's progress",
    viewGradesArrow: 'View grades',
    viewAttendanceArrow: 'View attendance',

    // ── Registration wizard (student) ────────────────────────────────────────
    step1Personal: 'Personal Info',
    step2Academic: 'Academic',
    step3Guardian: 'Guardian',
    step4Payment: 'Payment',
    gradeNewEntrant: 'New Entrant',
    gradeReEnroll: 'Re-enroll',
    gradeTransfer: 'Transfer Student',
    studentPhoto: 'Student Photo',
    idDoc: 'Resident ID / Birth Certificate',
    previousSchool: 'Previous School',
    grade8Score: 'Grade 8 Exam Score (avg)',
    grade8Certificate: 'Grade 8 Certificate / Transcript',
    releaseLetter: 'Official Release Letter',
    paymentMethod: 'Payment Method',
    transactionRef: 'Transaction Reference No.',
    paymentReceipt: 'Payment Receipt Photo',
    completeRegistration: 'Complete Registration',
    sectionPending: 'Section will be auto-assigned by the director after registration closes.',

    // ── Roles ────────────────────────────────────────────────────────────────
    ADMIN: 'Director',
    TEACHER: 'Teacher',
    STUDENT: 'Student',
    PARENT: 'Parent',

    // ── Gradebook ────────────────────────────────────────────────────────────
    failedToLoadData: 'Failed to load data',
    failedToLoadGrades: 'Failed to load grades',
    marksSaved: 'Marks saved',
    regradePermissionGranted: 'Regrade permission granted. Marks will re-lock after saving.',
    optionalFeedback: 'Optional feedback…',
    regradeRequestFor: 'Request permission to edit marks for',
    in: 'in',
    regradeReasonPlaceholder: 'Explain why this student\'s marks need correction…',
    submitting: 'Submitting…',
    submitRequest: 'Submit Request',
    regradeRequestSubmitted: 'Regrade request submitted — waiting for director approval',
    failedToSubmitRequest: 'Failed to submit request',
    homeroomGradebookView: 'Homeroom view — all subjects visible, enter marks for your subject',
    ownSubjectOnly: 'Enter marks for your assigned subject only',
    selectClassToViewGrades: 'Select a class to view grades.',
    yourSubject: 'yours',
    viewOnly: 'view',
    viewOnlyOtherSubjects: 'view only (other subjects)',
    lockedAfterSubmission: 'locked after submission',
    requestRegradeHomeroom: 'request regrade (homeroom only)',
    regradeActive: 'regrade active',
    requestRegradePermission: 'Request Regrade Permission',

    // ── Grade Submission Date page ────────────────────────────────────────────
    gradeEntryWindowSubtitle: 'Control when teachers can submit grades after final exams',
    openGradeEntryWarning: 'Opening this period allows teachers to submit grades. Make sure final exams are completed first.',
    gradeEntryWindowOpened: 'Grade submission period opened',
    gradeEntryWindowClosed: 'Grade submission period closed',
    gradeEntryWindowExtended: 'Grade submission period extended',
    noGradeEntryWindows: 'No submission periods yet. Open one after final exams are completed.',
    closeGradeEntryWarning: 'Closing this period will prevent teachers from submitting any more grades.',
    closeGradeEntryConfirm: 'Close grade submission for',
    extended: 'Extended',

    // ── Student detail / info ─────────────────────────────────────────────────
    studentDetails: 'Student Details',
    studentRegisteredSuccess: 'Student registered successfully. Share these credentials with the student.',
    studentRegistered: 'Student registered',
    studentUpdated: 'Student updated',
    studentDeleted: 'Student deleted',
    deleteStudentConfirm: 'Delete student',
    noStudentsFound: 'No students found.',
    studentCredentials: 'Student Login Credentials',
    editStudent: 'Edit Student',

    // ── Teacher detail ────────────────────────────────────────────────────────
    teacherDetails: 'Teacher Details',

    // ── Director Registration wizard ──────────────────────────────────────────
    enrollmentTypeLabel: 'Enrollment Type',
    selectEnrollmentType: 'Select how this student is enrolling:',
    newEntrantDesc: 'First time Grade 9 student (from Grade 8)',
    reEnrollDesc: 'Existing student re-enrolling for next grade',
    transferDesc: 'Student transferring from another school',
    repeatStudent: 'Repeat / Retained',
    repeatDesc: 'Student repeating the same grade',
    registerStudent: 'Register Student',
    registerAnother: 'Register Another',
    reviewSummary: 'Registration Summary',
    registrationFailed: 'Registration failed',

    // ── Notice board extras ───────────────────────────────────────────────────

    // ── Misc ─────────────────────────────────────────────────────────────────
    saveFailed: 'Save failed',
    deleteFailed: 'Delete failed',
    confirmDelete: 'Confirm Delete',
    noLabel: '—',

    // ── Missing keys from Login hero & error messages ────────────────────────
    welcomeTitle: 'Welcome to Arerti General Secondary & Preparatory School Portal',
    welcomeSubtitle: 'Manage students, grades, attendance and communication — securely, from any device.',
    loginBrandTitle1: 'Arerti General Secondary',
    loginBrandTitle2: '& Preparatory School',
    loginDigitalPortal: 'Digital Portal',
    loginErrorFallback: 'Login failed — check your ID and password',
    loginWelcome: 'Welcome,',
    copyrightText: 'Arerti General Secondary & Preparatory School',
    pleaseUseEmail: 'Please fill in both fields',

    // ── Missing from Dashboards ─────────────────────────────────────────────
    hiStudent: 'Hi',
    welcomeParent: 'Welcome',
    latestNotices: 'Latest Notices',
    linkChildInstructions: "Link your account to your child via their Student UID — go to My Children to get started.",
    presentDays: 'days',

    // ── Missing from MyAttendancePage ───────────────────────────────────────
    monthJan: 'Jan',
    monthFeb: 'Feb',
    monthMar: 'Mar',
    monthApr: 'Apr',
    monthMay: 'May',
    monthJun: 'Jun',
    monthJul: 'Jul',
    monthAug: 'Aug',
    monthSep: 'Sep',
    monthOct: 'Oct',
    monthNov: 'Nov',
    monthDec: 'Dec',
    weekdayShortSun: 'Sun',
    weekdayShortMon: 'Mon',
    weekdayShortTue: 'Tue',
    weekdayShortWed: 'Wed',
    weekdayShortThu: 'Thu',
    weekdayShortFri: 'Fri',
    weekdayShortSat: 'Sat',

    // ── Missing from registration wizards ───────────────────────────────────
    enrolledLabel: 'Enrolled',
    passedLabel: 'Passed',
    failedLabel: 'Failed',
    repeaterLabel: 'Repeater',
    studentsDidNotPass: 'students did not pass and can re-enroll as repeaters',
    studentEnrolled: 'enrolled successfully',
    enrollmentFailed: 'Enrollment failed',
    financeOffice: 'Finance Office',
    bankTransfer: 'Bank Transfer',
    phoneInvalid: 'Phone number must start with 9 or 7 and be 9 digits',
    studentPhotoRequired: 'Student photo required',
    idDocRequired: 'ID document required',
    grade8CertRequired: 'Grade 8 certificate required',
    releaseLetterRequired: 'Release letter required (for transfer)',
    streamRequired1112: 'Stream required for Grade 11–12',
    scoreMustBe0to100: 'Score must be between 0 and 100',
    paymentReceiptRequired: 'Payment receipt required',
    noActiveWindow: 'No active registration window',
    failedToLoadStudents: 'Failed to load students',
    selectGradeToRegister: 'Select the grade to register the student into:',
    selectPaymentMethod: 'Please select a payment method',
    enterTransactionRef: 'Please enter the transaction reference',
    telebirr: 'Telebirr',
    cbe: 'CBE (Commercial Bank)',
    other: 'Other',
    promoted: 'Promoted',
    // ── Notice board audience / priority labels ───────────────────────────────
    audienceGeneral: 'General',
    priorityLow: 'Low',
    priorityMedium: 'Medium',
    priorityHigh: 'High',
    // ── ResourcesPage audience dropdown ──────────────────────────────────────
    audienceStudents: 'Students',
    audienceTeachers: 'Teachers',
    audienceParents: 'Parents',
    // ── Class stream duplicate hint ────────────────────────────────────────
    classDuplicateHint: 'Grade 11 and 12 sections with the same letter but different streams (Natural/Social) are allowed as separate classes.',
  },

  am: {
    // ── Nav ──────────────────────────────────────────────────────────────────
    dashboard: 'ዳሽቦርድ',
    students: 'ተማሪዎች',
    teachers: 'አስተማሪዎች',
    classes: 'ክፍሎች',
    subjects: 'ትምህርቶች',
    gradebook: 'የውጤት ደብተር',
    attendance: 'ክትትል',
    noticeboard: 'ማስታወቂያ ሰሌዳ',
    resources: 'ግብዓቶች',
    auditlog: 'የኦዲት መዝገብ',
    registration: 'ምዝገባ',
    regrade: 'ዳግም ምዘና',
    userlookup: 'ተጠቃሚ ፈልግ',
    account: 'መለያ',
    logout: 'ውጣ',
    myGrades: 'ውጤቶቼ',
    myAttendance: 'ክትትሌ',
    notices: 'ማስታወቂያዎች',
    myChildren: 'ልጆቼ',
    reportCards: 'የሪፖርት ካርዶች',
    // ── Admin grouped nav labels ─────────────────────────────────────────────
    navRegistration: 'ምዝገባ',
    navAcademics: 'አካዳሚክ',
    navManagement: 'አስተዳደር',
    studentRegistration: 'የተማሪ ምዝገባ',
    teacherRegistration: 'የአስተማሪ ምዝገባ',

    // ── Login ────────────────────────────────────────────────────────────────
    signIn: 'ግባ',
    signInSubtitle: 'የተጠቃሚ ስምዎን ወይም ኢሜልዎን ይጠቀሙ።',
    usernameEmail: 'የተጠቃሚ ስም / ኢሜል',
    password: 'የይለፍ ቃል',
    signingIn: 'በመግባት ላይ…',
    troubleSignIn: 'ለመግባት ችግር አለዎት? ትምህርት ቤቱን ያነጋግሩ።',
    forDirectors: 'ለዳይሬክተሮች',
    forTeachers: 'ለአስተማሪዎች',
    forStudents: 'ለተማሪዎች',
    forParents: 'ለወላጆች',
    manageSchool: 'ሙሉ ትምህርት ቤቱን ያስተዳድሩ',
    gradesAttendance: 'ውጤቶች፣ ክትትልና ቁሳቁሶች',
    viewResults: 'ውጤቶችን ይዩ፣ ቁሳቁሶች ያግኙ',
    trackChild: 'የልጅዎን እድገት ይከታተሉ',

    // ── Common actions ───────────────────────────────────────────────────────
    save: 'አስቀምጥ',
    saving: 'በማስቀመጥ ላይ…',
    cancel: 'ሰርዝ',
    delete: 'አጥፋ',
    edit: 'አስተካክል',
    add: 'ጨምር',
    search: 'ፈልግ',
    searching: 'በመፈለግ ላይ…',
    loading: 'በመጫን ላይ…',
    noData: 'ምንም መረጃ አልተገኘም።',
    required: 'ያስፈልጋል',
    confirm: 'አረጋግጥ',
    close: 'ዝጋ',
    back: 'ተመለስ',
    next: 'ቀጥል',
    done: 'ተጠናቀቀ',
    register: 'ምዝገባ',
    submit: 'አስገባ',
    update: 'አዘምን',
    remove: 'አስወግድ',
    view: 'ይዩ',
    hide: 'ደብቅ',
    upload: 'ጫን',
    uploading: 'በመጫን ላይ…',
    download: 'አውርድ',
    downloading: 'በማውረድ ላይ…',
    approve: 'ፍቀድ',
    reject: 'ውድቅ አድርግ',
    review: 'ፍተሽ',
    unlink: 'አፍታታ',
    all: 'ሁሉም',
    prev: 'ቀዳሚ',
    page: 'ገጽ',
    of: 'ከ',
    by: 'በ',
    total: 'ጠቅላላ',
    assigned: 'ተሰይሟል',
    pending: 'በጥበቃ ላይ',
    active: 'ንቁ',
    disabled: 'ተዘጋ',
    copied: 'ተቀዷል!',
    copyToClipboard: 'ወደ ቅጂ ሰሌዳ ቅዳ',
    changeFile: 'ፋይል ቀይር',
    uploadFile: 'ፋይል ጫን',
    saveChanges: 'ለውጦችን አስቀምጥ',

    // ── Page titles ──────────────────────────────────────────────────────────
    studentsPage: 'ተማሪዎች',
    teachersPage: 'አስተማሪዎች',
    classesPage: 'ክፍሎች',
    subjectsPage: 'ትምህርቶች',
    attendancePage: 'ክትትል',
    noticeBoardPage: 'ማስታወቂያ ሰሌዳ',
    resourcesPage: 'ግብዓቶች',
    auditLogPage: 'የኦዲት መዝገብ',
    myGradesPage: 'ውጤቶቼ',
    myAttendancePage: 'ክትትሌ',
    accountPage: 'መለያዬ',
    myChildrenPage: 'ልጆቼ',
    userLookupPageTitle: 'ተጠቃሚ ፈልግ',

    // ── Attendance page ──────────────────────────────────────────────────────
    attendanceSubtitleAdmin: 'በክፍል ዕለታዊ ክትትሉን ምዝግብ',
    attendanceSubtitleTeacher: 'ለእርስዎ ክፍል ክትትሉን ምዝግብ',
    selectClass: 'ክፍል ምረጥ',
    dateLabel: 'ቀን',
    dayLabel: 'ቀን',
    markAllPresent: 'ሁሉንም ተገኝቷል ምዝግብ',
    markAllAbsent: 'ሁሉንም አልተገኘም ምዝግብ',
    allMarkedAs: 'ሁሉም ምልክት ተደርጓል',
    present: 'ተገኝቷል',
    absent: 'አልተገኘም',
    absentOther: 'አልተገኘም/ሌላ',
    late: 'ዘግይቷል',
    excused: 'ፈቃድ አለው',
    attendanceRate: 'የክትትል መጠን',
    noHomeroomAssigned: 'ለምንም ክፍል የክፍል አስተማሪ አይደሉም።',
    notHomeroomTeacher: '⚠️ ለምንም ክፍል የክፍል አስተማሪ አይደሉም። ዳይሬክተሩን ያነጋግሩ።',
    selectClassToMark: 'ክትትሉን ለመምዝገብ ክፍል ይምረጡ።',
    noStudentsInSection: 'በዚህ ክፍሉ ተማሪ የለም።',
    student: 'ተማሪ',
    statusLabel: 'ሁኔታ',
    actions: 'ድርጊቶች',
    failedToLoadClasses: 'ክፍሎችን ማምጣት አልተቻለም',
    failedToLoadAttendance: 'ክትትሉን ማምጣት አልተቻለም',
    failedToSaveAttendance: 'ክትትሉን ማስቀመጥ አልተቻለም',

    // ── My Attendance ────────────────────────────────────────────────────────
    noClassAssigned: 'ክፍል አልተሰጠም',
    daysLabel: 'ቀናት',
    attendanceLowWarning: 'ክትትልዎ ከ75% በታች ነው። ከአስተማሪዎ ወይም አሳዳጊዎ ጋር ይነጋገሩ።',
    noAttendanceRecords: 'እስካሁን የክትትል መዝገብ የለም።',
    noteLabel: 'ማስታወሻ',
    markedByLabel: 'ምልክት የደረሰ',
    studentProfileNotSetup: 'የተማሪ መግለጫዎ እስካሁን አልተዋቀረም። አስተዳዳሪውን ያነጋግሩ።',

    // ── Notice Board ─────────────────────────────────────────────────────────
    titleLabel: 'ርዕስ',
    bodyLabel: 'ይዘት',
    audienceLabel: 'ታዳሚ',
    priorityLabel: 'ቅድሚያ',
    pinNotice: 'ይህን ማስታወቂያ ወደ ላይ ቀጥቅጥ',
    pinned: 'ቀጥቅጦ',
    noticesCount: 'ማስታወቂያዎች',
    noNotices: 'እስካሁን ማስታወቂያ የለም።',
    postNotice: 'ማስታወቂያ ለጥፍ',
    editNotice: 'ማስታወቂያ አስተካክል',
    noticePosted: 'ማስታወቂያ ተለጥፏል',
    noticeUpdated: 'ማስታወቂያ ተስተካክሏል',
    noticeDeleted: 'ማስታወቂያ ተሰርዟል',
    deleteNoticeConfirm: 'ማስታወቂያ ሰርዝ',
    failedToLoadNotices: 'ማስታወቂያዎችን ማምጣት አልተቻለም',

    // ── Resources ────────────────────────────────────────────────────────────
    descriptionLabel: 'መግለጫ',
    subjectLabel: 'ትምህርት',
    fileLabel: 'ፋይል',
    maxFileSize: 'ከፍተኛ 25 ሜጋ.',
    noResources: 'እስካሁን ግብዓት የለም።',
    uploadResource: 'ግብዓት ጫን',
    resourceUploaded: 'ግብዓት ተጭኗል',
    resourceDeleted: 'ግብዓት ተሰርዟል',
    uploadFailed: 'መጫን አልተቻለም',
    downloadFailed: 'ማውረድ አልተቻለም',
    deleteResourceConfirm: 'ግብዓት ሰርዝ',
    failedToLoadResources: 'ግብዓቶችን ማምጣት አልተቻለም',
    choosefile: 'ፋይል ይምረጡ',
    files: 'ፋይሎች',

    // ── Subjects ─────────────────────────────────────────────────────────────
    subjectName: 'የትምህርት ስም',
    codeLabel: 'ኮድ',
    applicableGrades: 'የሚተገበሩ ክፍሎች',
    noSubjectsFound: 'ምንም ትምህርት አልተገኘም።',
    subjectsDefined: 'ትምህርቶች ተለይተዋል',
    addSubject: 'ትምህርት ጨምር',
    editSubject: 'ትምህርት አስተካክል',
    subjectAdded: 'ትምህርት ታክሏል',
    subjectUpdated: 'ትምህርት ተስተካክሏል',
    subjectDeleted: 'ትምህርት ተሰርዟል',
    deleteSubjectConfirm: 'ትምህርት ሰርዝ',
    failedToLoadSubjects: 'ትምህርቶችን ማምጣት አልተቻለም',

    // ── Classes ──────────────────────────────────────────────────────────────
    grade: 'ክፍል',
    section: 'ክፍለ ትምህርት',
    academicYear: 'ትምህርት ዓመት',
    homeroomTeacher: 'የክፍል አስተማሪ',
    maxCapacity: 'ከፍተኛ ቁጥር',
    stream: 'ዘርፍ',
    naturalScience: 'ተፈጥሮ ሳይንስ',
    socialScience: 'ማህበራዊ ሳይንስ',
    selectStream: 'ዘርፍ ምረጥ',
    requiredForGrade1112: 'ለ11-12 ክፍል ያስፈልጋል',
    noneLabel: 'የለም',
    homeroomNote: 'የክፍል አስተማሪ ለዚህ ክፍል ብቻ ክትትሉን ማስቀመጥ ይችላሉ።',
    subjectAssignments: 'የትምህርት ምደባ',
    gradeCurriculum: 'የክፍል ሥርዓተ ትምህርት',
    endTerm: 'ዓመቱን ጨርስ',
    endAcademicYearTerm: 'የትምህርት ዓመቱን ጨርስ',
    autoAssignStudents: 'ተማሪዎችን ልዩ ምደባ',
    sectionsConfigured: 'ክፍሎች ተዘጋጅተዋል',
    addClass: 'ክፍል ጨምር',
    editClass: 'ክፍል አስተካክል',
    classCreated: 'ክፍል ተፈጥሯል',
    classUpdated: 'ክፍል ተስተካክሏል',
    classDeleted: 'ክፍል ተሰርዟል',
    deleteClassConfirm: 'ሰርዝ',
    noClassesYet: 'እስካሁን ክፍሎች የሉም።',
    failedToLoadAssignments: 'ምደባዎችን ማምጣት አልተቻለም',
    teacherAssigned: 'አስተማሪ ተሰይሟል',
    failedToAssignTeacher: 'አስተማሪ መሰየም አልተቻለም',
    subjectsNeedTeacher: 'ትምህርቶች አስተማሪ ያስፈልጋቸዋል',
    noSubjectsAssigned: 'እስካሁን ትምህርቶች አልተሰጡም።',
    curriculumAutoApplied: 'ሥርዓተ ትምህርት ክፍሉ ሲፈጠር ራሱ ይተገበራል።',
    assignTeacher: 'አስተማሪ ሰይም',
    noCurriculumForGrade: 'ለዚህ ክፍል ሥርዓተ ትምህርት አልተዘጋጀም',
    subjectsAppliedFromCurriculum: 'ትምህርቶች ከ',
    failedToApplyCurriculum: 'ሥርዓተ ትምህርት መተግበር አልተቻለም',
    failedToLoadCurriculum: 'ሥርዓተ ትምህርት ማምጣት አልተቻለም',
    curriculumDescription: 'አዲስ ክፍል ሲፈጠር ምን ትምህርቶች ይሰጡ እንደሚሆን ይወስኑ።',
    selectStreamFirst: 'ዘርፍ ይምረጡ',
    subjectAddedToCurriculum: 'ትምህርት ወደ ሥርዓተ ትምህርት ታክሏል',
    subjectRemovedFromCurriculum: 'ትምህርት ከሥርዓተ ትምህርት ተወግዷል',
    addSubjectToCurriculum: 'ትምህርት ወደ ሥርዓተ ትምህርት ጨምር',
    noSubjectsInCurriculum: 'ምንም ትምህርቶች ለ ክፍል',
    selectStreamToView: 'የ ክፍልን ሥርዓተ ትምህርት ለማየት ዘርፍ ይምረጡ',
    curriculum: 'ሥርዓተ ትምህርት',
    failedToAdd: 'ማከል አልተቻለም',
    failedToRemove: 'ማስወገድ አልተቻለም',
    endOfYearAction: 'የዓመቱ ማጠናቀቂያ',
    endTermNote1: 'ሁሉም የዓመቱ ምደባዎች ይከማቻሉ',
    endTermNote2: 'ሁሉም ተማሪዎች ከክፍሎቻቸው ይወጣሉ',
    endTermNote3: 'የክፍሎች እና ምደባ ታሪክ ይቀመጣሉ',
    endTermNote4: 'ተማሪዎችን ወደ አዲሱ ክፍል ዳግም መሰየም ይኖርብዎታል',
    termEndedSuccess: 'ዓመቱ ተጠናቀቀ',
    failedToEndTerm: 'ዓመቱን ማጠናቀቅ አልተቻለም',
    termEndedFor: 'ዓመቱ ተጠናቀቀ ለ',
    subjectAssignmentsArchived: 'የትምህርት ምደባዎች ተከማቸዋል',
    studentsUnassigned: 'ተማሪዎች ተለቀዋል',
    academicYearToEnd: 'ለማጠናቀቅ ዓመት',
    processing: 'በሂደት ላይ…',

    // ── Audit Log ────────────────────────────────────────────────────────────
    auditEvents: 'ክስተቶች',
    systemActivityTrail: 'የሥርዓቱ እንቅስቃሴ',
    allEntityTypes: 'ሁሉም ዓይነቶች',
    noAuditEvents: 'እስካሁን ክስተቶች የሉም።',
    whenLabel: 'መቼ',
    actorLabel: 'ተዋናይ',
    actionLabel: 'ድርጊት',
    entityLabel: 'አካል',
    detailsLabel: 'ዝርዝሮች',
    failedToLoadAuditLog: 'ኦዲት መዝገቡን ማምጣት አልተቻለም',

    // ── Account ──────────────────────────────────────────────────────────────
    accountSubtitle: 'መግለጫዎን ይዩ እና የይለፍ ቃልዎን ያስተዳድሩ',
    profileLabel: 'መግለጫ',
    roleLabel: 'ሚና',
    nameLabel: 'ሙሉ ስም',
    changePassword: 'የይለፍ ቃል ቀይር',
    currentPassword: 'አሁን ያለ የይለፍ ቃል',
    newPasswordLabel: 'አዲስ የይለፍ ቃል',
    confirmNewPassword: 'አዲስ የይለፍ ቃል አረጋግጥ',
    min6chars: 'ቢያንስ 6 ቁምፊ',
    updatePassword: 'የይለፍ ቃል አዘምን',
    passwordChanged: 'የይለፍ ቃል ተቀይሯል',
    failedToChangePassword: 'የይለፍ ቃል መቀየር አልተቻለም',
    passwordTooShort: 'የይለፍ ቃሉ ቢያንስ 6 ቁምፊ መሆን አለበት',
    passwordsDoNotMatch: 'አዲሱ የይለፍ ቃሎች አይዛመዱም',
    passwordAcceptable: 'ተቀባይነት ያለው',
    passwordStrong: 'ጠንካራ',

    // ── My Grades ────────────────────────────────────────────────────────────
    semester: 'ሴሜስተር',
    year: 'ዓመት',
    average: 'አማካይ',
    subjectsLabel: 'ትምህርቶች',
    overallAverage: 'አጠቃላይ አማካይ',
    noGradesForSemester: 'ለሴሜስተር ምንም ውጤት አልተቀመጠም',
    scoreLabel: 'ውጤት',
    gradeLabel: 'ደረጃ',
    commentLabel: 'አስተያየት',
    failedToLoadStudent: 'የተማሪ መረጃ ማምጣት አልተቻለም',
    midExam: 'የወቅት ፈተና',
    finalExam: 'የዓመት ፈተና',
    assignment: 'የቤት ሥራ',
    testQuiz: 'ፈተና/ጥያቄ',
    saveMarks: 'ውጤት አስቀምጥ',
    marksLocked: 'ውጤቶቹ ተቆልፈዋል። ለማስተካከል ከዳይሬክተሩ ፈቃድ ይጠይቁ።',
    requestRegrade: 'ድጋሚ ምዘና ጠይቅ',

    // ── Parent Children ──────────────────────────────────────────────────────
    linkedChildren: 'የተያያዙ',
    linkAChild: 'ልጅ አያይዝ',
    linkChild: 'ልጅ አያይዝ',
    linking: 'በማያያዝ ላይ…',
    childLinked: 'ልጅ ተያይዟል',
    linkFailed: 'ማያያዝ አልተቻለም – UID ያረጋግጡ',
    childUnlinked: 'ልጅ ተለቋል',
    unlinkFailed: 'ማልቀቅ አልተቻለም',
    confirmUnlink: 'ማልቀቅ አረጋግጥ',
    unlinkConfirm: 'አፍታታ',
    noChildrenLinked: 'እስካሁን ልጆች አልተያያዙም።',
    studentUidLabel: 'የተማሪ UID',
    studentUidHint: 'ይህን UID ከትምህርት ቤቱ ቢሮ ወይም ከምዝገባ ደብዳቤ ያግኙ።',
    failedToLoadChildren: 'ልጆችን ማምጣት አልተቻለም',
    relationship: 'ዝምድና',

    // ── Parent Report Card ───────────────────────────────────────────────────
    reportCardsSubtitle: 'የልጅዎን ትምህርታዊ እድገት ይዩ',
    childLabel: 'ልጅ',
    teacherCommentLabel: 'የአስተማሪ አስተያየት',
    loadingReportCard: 'የሪፖርት ካርድ በመጫን ላይ…',
    noChildrenForReportCard: 'ልጆች አልተያያዙም። ወደ ልጆቼ ሄደው UID በመጠቀም ያያይዙ።',

    // ── User Lookup ──────────────────────────────────────────────────────────
    userLookupSubtitle: 'ማንኛውም ተጠቃሚ ፈልጉ።',
    searchByNameUsernameEmail: 'በስም፣ ተጠቃሚ ስም ወይም ኢሜል ፈልግ',
    noUsersFound: 'ምንም ተጠቃሚ አልተገኘም',
    viewResetPassword: 'ተሽጋሸዝ / ፕ ቀይር',
    credentialsFor: 'ምስጢሮች –',
    passwordResetSuccess: 'የይለፍ ቃል ዳግም ተጀምሯል',
    resetFailed: 'ዳግም ጀምር አልተቻለም',
    passwordResetShareNote: 'የይለፍ ቃሉ ተቀይሯል። ተጠቃሚው ቀጥሎ ሲገቡ ይቀይሩታል።',
    enterNewPasswordForUser: 'ለዚህ ተጠቃሚ አዲስ የይለፍ ቃል ያስገቡ',
    passwordResetTip: 'ምክር፡ Arerti@2026 ይሞክሩ',
    resetting: 'ዳግም በማስጀመር ላይ…',
    resetPassword: 'የይለፍ ቃል ዳግም አስጀምር',
    searchFailed: 'መፈለግ አልተቻለም',

    // ── Regrade ──────────────────────────────────────────────────────────────
    regradeSubtitle: 'ቆልፎ ምልክቶችን ለማስተካከል የሚደረጉ ጥያቄዎችን ፍቀዱ',
    noRequests: 'ምንም',
    teacherLabel: 'አስተማሪ',
    classLabel: 'ክፍል',
    reasonLabel: 'ምክንያት',
    noteToTeacher: 'ለአስተማሪ ማስታወሻ (አማራጭ)',
    addNoteForTeacher: 'ለአስተማሪ ማስታወሻ ጨምር',
    regradeApproved: 'ዳግም ምዘና ጥያቄ ፀድቋል',
    regradeRejected: 'ዳግም ምዘና ጥያቄ ውድቅ ሆኗል',
    resolveFailed: 'መፍታት አልተቻለም',
    reviewRegradeRequest: 'ዳግም ምዘና ጥያቄ ፍተሽ',
    failedToLoadRegrade: 'ዳግም ምዘና ጥያቄዎችን ማምጣት አልተቻለም',

    // ── Teachers page ────────────────────────────────────────────────────────
    staffMembers: 'የሰራተኞች ቁጥር',
    addTeacher: 'አስተማሪ ጨምር',
    registerTeacher: 'አስተማሪ ምዝገባ',
    editTeacher: 'አስተማሪ አስተካክል',
    teacherRegistered: 'አስተማሪ ተመዝግቧል',
    teacherUpdated: 'አስተማሪ ተስተካክሏል',
    teacherDeleted: 'አስተማሪ ተሰርዟል',
    deleteTeacherConfirm: 'አስተማሪ ሰርዝ',
    noTeachersFound: 'ምንም አስተማሪ አልተገኘም።',
    failedToLoadTeachers: 'አስተማሪዎችን ማምጣት አልተቻለም',
    teacherRegisteredSuccess: 'አስተማሪ ተመዝግቧል። እነዚህን ምስጢሮች ያካፍሉ።',
    passwordShownOnce: 'የይለፍ ቃሉ አንድ ጊዜ ብቻ ይታያል።',
    teacherCredentials: 'የአስተማሪ መግቢያ ምስጢሮች',
    personalInfo: 'የግል መረጃ',
    professionalInfo: 'ሙያዊ መረጃ',
    documentsSection: 'ሰነዶች',
    credentialsAutoGenerated: 'ተጠቃሚ ስምና የይለፍ ቃል ራሱ ይፈጠራሉ።',
    selectLabel: 'ምረጥ',
    firstName: 'የራስ ስም',
    fatherName: 'የአባት ስም',
    grandfatherName: 'የአያት ስም',
    gender: 'ጾታ',
    dateOfBirth: 'የልደት ቀን',
    email: 'ኢሜል',
    region: 'ክልል',
    city: 'ከተማ / ወረዳ',
    kebele: 'ቀበሌ',
    houseNo: 'የቤት ቁጥር',
    phone: 'ስልክ',
    qualification: 'ብቃት',
    specialization: 'ስፔሻሊዜሽን',
    hireDate: 'የቅጥር ቀን',
    teacherPhoto: 'የአስተማሪ ፎቶ',
    qualificationCert: 'የብቃት ሰርቲፊኬት',
    idDocument: 'መታወቂያ / የልደት ምስክርወረቀት',
    photoLabel: 'ፎቶ',
    uploaded: 'ተጭኗል',
    failedToUpload: 'መጫን አልተቻለም',

    // ── Students ─────────────────────────────────────────────────────────────
    addStudent: 'ተማሪ ጨምር',
    enrolled: 'ተመዝግቧል',
    fullName: 'ሙሉ ስም',
    username: 'የተጠቃሚ ስም',
    guardianPhone: 'የወላጅ ስልክ',
    enrollmentYear: 'የምዝገባ ዓመት',
    classSection: 'ክፍል / ክፍለ ትምህርት',
    male: 'ወንድ',
    female: 'ሴት',
    unassigned: 'ያልተመደበ',
    leaveBlankToKeep: 'ባዶ ይተው ለማቆየት',
    parentName: 'የወላጅ / አሳዳጊ ሙሉ ስም',
    parentPhone: 'ስልክ ቁጥር',

    // ── Registration ─────────────────────────────────────────────────────────
    registrationSubtitle: 'የምዝገባ መስኮቶችን እና ምደባዎችን ያስተዳድሩ',
    registrationOpened: 'ምዝገባ ተጀምሯል',
    registrationClosed: 'ምዝገባ ተዘግቷል',
    openRegistration: 'የምዝገባ መስኮት ክፈት',
    openRegistrationWindow: 'የምዝገባ መስኮት ክፈት',
    closeRegistration: 'ምዝገባ ዝጋ',
    postponeRegistration: 'ምዝገባ አራዝም',
    newEndDate: 'አዲስ የማጠናቀቂያ ቀን እና ሰዓት',
    postponeReason: 'የማራዘሚያ ምክንያት',
    postponeReasonPlaceholder: 'ምሳሌ: ለዘጋቢ አመልካቾች 3 ቀናት ተራዝሟል',
    assignedTeachers: 'የተሰጡ አስተማሪዎች',
    allowedGrades: 'የሚፈቀዱ ክፍሎች',
    selectTeacher: 'አስተማሪ ምረጥ',
    startDateTime: 'የጀምሪያ ቀን እና ሰዓት',
    endDateTime: 'የማጠናቀቂያ ቀን እና ሰዓት',
    optionalNote: 'አማራጭ ማስታወሻ',
    opening: 'በመክፈት ላይ…',
    assigning: 'በመሰየም ላይ…',
    postponing: 'በማራዘም ላይ…',
    activeWindows: 'ክፍት መስኮቶች',
    pastWindows: 'ያለፉ መስኮቶች',
    noWindowsYet: 'እስካሁን መስኮቶች የሉም።',
    closeRegistrationWindow: 'የምዝገባ መስኮት ዝጋ',
    closeWindowWarning: 'ይህን መስኮት ዘጋ አስተማሪዎቹ ወዲያው ማስመዝገብ አይችሉም።',
    closeWindowConfirm: 'ዝጋ',
    newEndDateRequired: 'አዲስ ቀን እና ሰዓት ያስፈልጋል',
    registrationPostponed: 'ምዝገባ ተራዝሟል',
    failedToPostpone: 'ማራዘም አልተቻለም',
    currentEnd: 'አሁን ያለ ቀን',
    newEndMustBeLater: 'አዲሱ ቀን ከአሁኑ ቀን በኋላ መሆን አለበት።',
    registrationWindowOpened: 'የምዝገባ መስኮት ተከፍቷል',
    registrationWindowClosed: 'የምዝገባ መስኮት ተዘግቷል',
    failedToOpenWindow: 'መክፈት አልተቻለም',
    failedToClose: 'መዝጋት አልተቻለም',
    assignmentRemoved: 'ምደባ ተወግዷል',
    failedToLoad: 'ማምጣት አልተቻለም',
    failedToLoadEnrollments: 'ምዝገቦቹን ማምጣት አልተቻለም',
    selectAtLeastOneGrade: 'ቢያንስ አንድ ክፍል ምረጥ',
    failedToAssign: 'መሰየም አልተቻለም',
    liveNow: 'አሁን ክፍት',
    postponed: 'ተራዝሟል',
    openedBy: 'የከፈተ',
    enrollments: 'ምዝገቦች',
    enrollmentAudit: 'ምዝገባ ኦዲት',
    noEnrollments: 'እስካሁን ምዝገቦች የሉም',
    studentsRegistered: 'ተማሪዎች ተመዝግበዋል',
    endDateRequired: 'የማጠናቀቂያ ቀን ያስፈልጋል',
    autoAssignStudentsTitle: 'ተማሪዎችን ወደ ክፍሎች ምደባ',
    autoAssignTitle: 'ተማሪዎችን ወደ ክፍሎች ምደባ',
    autoAssignDescription: 'ተማሪዎቹ ባለፈው ክፍል ውጤት ተደርድረው በሁሉም ክፍሎች ይሰራጫሉ።',
    autoAssignFailed: 'ምደባ አልተቻለም',
    autoAssignWarning: 'ክፍሎቹ ለ ክፍል',
    goToClasses: 'ወደ ክፍሎች ሄደው ክፍሎቹን ይፍጠሩ።',
    runAutoAssign: 'ምደባ አሂድ',
    perSection: 'በክፍል',
    studentsCount: 'ተማሪዎች',

    // ── Grade Submission Date (formerly Grade Entry Window) ──────────────────
    gradeEntryWindow: 'የውጤት ማስረከቢያ ቀን',
    openGradeEntry: 'ማስረከቢያ ጊዜ ክፈት',
    closeGradeEntry: 'ማስረከቢያ ጊዜ ዝጋ',
    postponeGradeEntry: 'ማስረከቢያ ጊዜ አራዝም',
    gradeEntryOpen: 'የውጤት ማስረከቢያ ክፍት ነው',
    gradeEntryClosed: 'የውጤት ማስረከቢያ ተዘግቷል። ዳይሬክተሩ እስኪከፍቱ ይጠብቁ።',

    // ── Dashboard ────────────────────────────────────────────────────────────
    welcomeAdmin: 'እንኳን ደህና መጡ',
    directorOverview: 'የሥርዓቱ አጠቃላይ እይታ',
    manageStudents: 'አስተዳድር',
    manageTeachers: 'አስተዳድር',
    manageClasses: 'አስተዳድር',
    manageNotices: 'አስተዳድር',
    studentRegistrationCard: 'የተማሪ ምዝገባ',
    studentRegistrationDesc: 'መስኮቶችን ክፈት፣ አስተማሪዎችን ሰይም፣ ተማሪዎችን ምዝገባ',
    gradebookCard: 'የውጤት ደብተር',
    gradebookDesc: 'ውጤቶችን አስገባ እና ይገምግሙ',
    attendanceCard: 'ክትትል',
    attendanceDesc: 'ክትትሉን ምዝግብ እና ይገምግሙ',
    subjectsCard: 'ትምህርቶች',
    subjectsDesc: 'ትምህርቶችን እና ውጤቶችን ያስተዳድሩ',
    regradeCard: 'ድጋሚ ምዘና ጥያቄዎች',
    regradeDesc: 'የምልክት ማስተካከያ ጥያቄዎችን ይከልሱ',
    resourcesCard: 'ግብዓቶች',
    resourcesDesc: 'የጥናት ቁሳቁሶችን ጫን እና ያስተዳድሩ',
    auditLogCard: 'የኦዲት መዝገብ',
    auditLogDesc: 'የሥርዓቱ እንቅስቃሴ ይከልሱ',
    gradeEntryCard: 'የውጤት ማስረከቢያ',
    gradeEntryDesc: 'ከፈተና በኋላ የውጤት ማስረከቢያ ጊዜ ክፈት',
    userLookupCard: 'ተጠቃሚ ፈልግ',
    userLookupDesc: 'ተጠቃሚ ስም ፈልግ፣ የተረሳ Password ዳግም ጀምር',
    teacherWorkspace: 'የአስተማሪ ቦታ',
    helloTeacher: 'ሰላም',
    enterGrades: 'ውጤቶችን አስገባ እና ያስተዳድሩ',
    markAttendance: 'ዕለታዊ ክትትሉን ምዝግብ',
    viewNotices: 'ማስታወቂያ ሰሌዳ ይዩ',
    yourSchoolSnapshot: 'የትምህርት ቤቱ ቅጽበታዊ ዕይታ',
    trackChildProgress: 'የልጅዎን እድገት ይከታተሉ',
    viewGradesArrow: 'ውጤቶችን ይዩ',
    viewAttendanceArrow: 'ክትትሉን ይዩ',

    // ── Registration wizard ──────────────────────────────────────────────────
    step1Personal: 'የግል መረጃ',
    step2Academic: 'ትምህርታዊ',
    step3Guardian: 'አሳዳጊ',
    step4Payment: 'ክፍያ',
    gradeNewEntrant: 'አዲስ ተማሪ',
    gradeReEnroll: 'ድጋሚ ምዝገባ',
    gradeTransfer: 'ዝውውር ተማሪ',
    studentPhoto: 'የተማሪ ፎቶ',
    idDoc: 'መታወቂያ / የልደት ምስክርወረቀት',
    previousSchool: 'ቀደሚ ትምህርት ቤት',
    grade8Score: 'የ8ኛ ክፍል ፈተና ውጤት (አማካይ)',
    grade8Certificate: 'የ8ኛ ክፍል ምስክርወረቀት',
    releaseLetter: 'ሥምረት ደብዳቤ',
    paymentMethod: 'የክፍያ ዘዴ',
    transactionRef: 'የ거래 ማጣቀሻ ቁጥር',
    paymentReceipt: 'የክፍያ ደረሰኝ ፎቶ',
    completeRegistration: 'ምዝገባ አጠናቅ',
    sectionPending: 'ምዝገባ ከተዘጋ በኋላ ዳይሬክተሩ ክፍልን ይመድባሉ።',

    // ── Roles ────────────────────────────────────────────────────────────────
    ADMIN: 'ዳይሬክተር',
    TEACHER: 'አስተማሪ',
    STUDENT: 'ተማሪ',
    PARENT: 'ወላጅ',

    // ── Gradebook ────────────────────────────────────────────────────────────
    failedToLoadData: 'መረጃ ማምጣት አልተቻለም',
    failedToLoadGrades: 'ውጤቶችን ማምጣት አልተቻለም',
    marksSaved: 'ውጤቶቹ ተቀምጠዋል',
    regradePermissionGranted: 'ፈቃድ ተሰጥቷል። ከተቀመጠ በኋላ ዳግም ይቆለፋሉ።',
    optionalFeedback: 'አማራጭ አስተያየት…',
    regradeRequestFor: 'ድጋሚ ምዘና ፈቃድ ጥያቄ ለ',
    in: 'ትምህርት',
    regradeReasonPlaceholder: 'ለምን የዚህ ተማሪ ውጤት ማስተካከል ያስፈልጋል?',
    submitting: 'በማስገባት ላይ…',
    submitRequest: 'ጥያቄ አስገባ',
    regradeRequestSubmitted: 'ጥያቄ ቀርቧል — ከዳይሬክተሩ ፈቃድ ይጠበቃል',
    failedToSubmitRequest: 'ጥያቄ ማስገባት አልተቻለም',
    homeroomGradebookView: 'የክፍል አስተማሪ እይታ — ሁሉም ትምህርቶች ይታያሉ',
    ownSubjectOnly: 'ለእርስዎ ትምህርት ብቻ ውጤት ያስገቡ',
    selectClassToViewGrades: 'ውጤቶችን ለማየት ክፍል ይምረጡ።',
    yourSubject: 'የእርስዎ',
    viewOnly: 'ማየት ብቻ',
    viewOnlyOtherSubjects: 'ማየት ብቻ (ሌሎች ትምህርቶች)',
    lockedAfterSubmission: 'ከተቀመጠ በኋላ ይቆለፋል',
    requestRegradeHomeroom: 'ድጋሚ ምዘና ጠይቅ (የክፍል አስተማሪ)',
    regradeActive: 'ድጋሚ ምዘና ክፍት',
    requestRegradePermission: 'ድጋሚ ምዘና ፈቃድ ጠይቅ',

    // ── Grade Submission Date page ────────────────────────────────────────────
    gradeEntryWindowSubtitle: 'አስተማሪዎቹ ፈተና ካለቀ በኋላ ውጤት ሊያስረክቡ የሚችሉበትን ጊዜ ይቆጣጠሩ',
    openGradeEntryWarning: 'ይህ ጊዜ ሲከፈት አስተማሪዎቹ ውጤት ማስረከብ ይጀምራሉ። ፈተናዎቹ አልቀዋል ብለው ያረጋግጡ።',
    gradeEntryWindowOpened: 'የውጤት ማስረከቢያ ጊዜ ተከፍቷል',
    gradeEntryWindowClosed: 'የውጤት ማስረከቢያ ጊዜ ተዘግቷል',
    gradeEntryWindowExtended: 'የውጤት ማስረከቢያ ጊዜ ተራዝሟል',
    noGradeEntryWindows: 'እስካሁን ምንም የማስረከቢያ ጊዜ የለም። ፈተናዎቹ ካለቁ በኋላ ይክፈቱ።',
    closeGradeEntryWarning: 'ይህ ጊዜ ሲዘጋ አስተማሪዎቹ ተጨማሪ ውጤት ማስረከብ አይችሉም።',
    closeGradeEntryConfirm: 'ውጤት ማስረከቢያ ዝጋ',
    extended: 'ተራዝሟል',

    // ── Student ───────────────────────────────────────────────────────────────
    studentDetails: 'የተማሪ ዝርዝር',
    studentRegisteredSuccess: 'ተማሪ ተመዝግቧል። ምስጢሮቹን ለተማሪው ያካፍሉ።',
    studentRegistered: 'ተማሪ ተመዝግቧል',
    studentUpdated: 'ተማሪ ተስተካክሏል',
    studentDeleted: 'ተማሪ ተሰርዟል',
    deleteStudentConfirm: 'ተማሪ ሰርዝ',
    noStudentsFound: 'ምንም ተማሪ አልተገኘም።',
    studentCredentials: 'የተማሪ መግቢያ ምስጢሮች',
    editStudent: 'ተማሪ አስተካክል',

    // ── Teacher ───────────────────────────────────────────────────────────────
    teacherDetails: 'የአስተማሪ ዝርዝር',

    // ── Director Registration wizard ──────────────────────────────────────────
    enrollmentTypeLabel: 'የምዝገባ ዓይነት',
    selectEnrollmentType: 'ይህ ተማሪ እንዴት እንደሚመዘገብ ይምረጡ:',
    newEntrantDesc: 'ለመጀመሪያ ጊዜ 9ኛ ክፍል (ከ8ኛ ክፍል)',
    reEnrollDesc: 'ወደ ቀጣይ ክፍል የሚሄድ ተማሪ',
    transferDesc: 'ከሌላ ትምህርት ቤት የሚዛወር ተማሪ',
    repeatStudent: 'ድጋሚ / ቀርቷል',
    repeatDesc: 'ተማሪ ተመሳሳይ ክፍል ዳግም ይደግማሉ',
    registerStudent: 'ተማሪ ምዝገባ',
    registerAnother: 'ሌላ ምዝግብ',
    reviewSummary: 'የምዝገባ ማጠቃለያ',
    registrationFailed: 'ምዝገባ አልተቻለም',

    // ── Misc ─────────────────────────────────────────────────────────────────
    saveFailed: 'ማስቀመጥ አልተቻለም',
    deleteFailed: 'ማጥፋት አልተቻለም',
    confirmDelete: 'ሰርዝ አረጋግጥ',
    noLabel: '—',

    // ── Missing keys from Login hero & error messages ────────────────────────
    welcomeTitle: 'እንኳን ደህና መጡ ወደ አረርቲ አጠቃላይ ሁለተኛ ደረጃ እና ቅድመ-ዩኒቨርሲቲ ትምህርት ቤት ፖርታል',
    welcomeSubtitle: 'ተማሪዎችን፣ ውጤቶችን፣ ክትትልና ግንኙነትን ያስተዳድሩ — ደህንነቱ በተጠበቀ ሁኔታ፣ ከማንኛውም መሳሪያ።',
    loginBrandTitle1: 'አረርቲ አጠቃላይ ሁለተኛ ደረጃ',
    loginBrandTitle2: 'እና ቅድመ-ዩኒቨርሲቲ ትምህርት ቤት',
    loginDigitalPortal: 'ዲጂታል ፖርታል',
    loginErrorFallback: 'መግቢያ አልተቻለም — ​​ID እና የይለፍ ቃልዎን ያረጋግጡ',
    loginWelcome: 'እንኳን ደህና መጡ,',
    copyrightText: 'አረርቲ አጠቃላይ ሁለተኛ ደረጃ እና ቅድመ-ዩኒቨርሲቲ ትምህርት ቤት',
    pleaseUseEmail: 'ሁለቱንም ሳጥኖች ይሙሉ',

    // ── Missing from Dashboards ─────────────────────────────────────────────
    hiStudent: 'ሰላም',
    welcomeParent: 'እንኳን ደህና መጡ',
    latestNotices: 'የቅርብ ማስታወቂያዎች',
    linkChildInstructions: 'የልጅዎን Student UID ተጠቅመው ይያያዙ — ወደ ልጆቼ ሄደው ይጀምሩ።',
    presentDays: 'ቀናት',

    // ── Missing from MyAttendancePage ───────────────────────────────────────
    monthJan: 'ጃን',
    monthFeb: 'ፌብ',
    monthMar: 'ማር',
    monthApr: 'ኤፕ',
    monthMay: 'ሜይ',
    monthJun: 'ጁን',
    monthJul: 'ጁል',
    monthAug: 'ኦግ',
    monthSep: 'ሴፕ',
    monthOct: 'ኦክ',
    monthNov: 'ኖቭ',
    monthDec: 'ዲሴ',
    weekdayShortSun: 'እሑድ',
    weekdayShortMon: 'ሰኞ',
    weekdayShortTue: 'ማክሰ',
    weekdayShortWed: 'ረቡዕ',
    weekdayShortThu: 'ሐሙስ',
    weekdayShortFri: 'ዓርብ',
    weekdayShortSat: 'ቅዳሜ',

    // ── Missing from registration wizards ───────────────────────────────────
    enrolledLabel: 'ተመዝግቧል',
    passedLabel: 'አለፈ',
    failedLabel: 'ወደቀ',
    repeaterLabel: 'ደጋሚ',
    studentsDidNotPass: 'ተማሪዎች ምዝገባ ደጋሚ ሆነው ሊምዘገቡ ይችላሉ',
    studentEnrolled: 'ተመዝግቧል',
    enrollmentFailed: 'ምዝገባ አልተቻለም',
    financeOffice: 'የፋይናንስ ቢሮ',
    bankTransfer: 'የባንክ ዝውውር',
    phoneInvalid: 'ስልኩ 9 ወይም 7 ሊጀምርና 9 ቁጥሮች ሊኖሩት ይገባል',
    studentPhotoRequired: 'የተማሪ ፎቶ ያስፈልጋል',
    idDocRequired: 'መታወቂያ ሰነድ ያስፈልጋል',
    grade8CertRequired: 'የ8ኛ ክፍል ምስክርወረቀት ያስፈልጋል',
    releaseLetterRequired: 'ሥምረት ደብዳቤ ያስፈልጋል (ለዝውውር)',
    streamRequired1112: 'ዘርፍ ለ11-12 ክፍል ያስፈልጋል',
    scoreMustBe0to100: 'ውጤቱ ከ0 እስከ 100 መሆን አለበት',
    paymentReceiptRequired: 'የክፍያ ደረሰኝ ያስፈልጋል',
    noActiveWindow: 'ክፍት የምዝገባ መስኮት የለም',
    failedToLoadStudents: 'ተማሪዎችን ማምጣት አልተቻለም',
    selectGradeToRegister: 'ተማሪውን ለመምዝገብ ክፍሉን ይምረጡ:',
    selectPaymentMethod: 'የክፍያ ዘዴ ይምረጡ',
    enterTransactionRef: 'የ거래 ማጣቀሻ ቁጥር ያስገቡ',
    telebirr: 'ቴሌብር',
    cbe: 'ኢትዮጵያ ንግድ ባንክ',
    other: 'ሌላ',
    promoted: 'አለፈ',
    // ── Notice board audience / priority labels ───────────────────────────────
    audienceGeneral: 'ሁሉም',
    priorityLow: 'ዝቅተኛ',
    priorityMedium: 'መካከለኛ',
    priorityHigh: 'ከፍተኛ',
    // ── ResourcesPage audience dropdown ──────────────────────────────────────
    audienceStudents: 'ተማሪዎች',
    audienceTeachers: 'አስተማሪዎች',
    audienceParents: 'ወላጆች',
    // ── Class stream duplicate hint ────────────────────────────────────────
    classDuplicateHint: 'ለ11-12 ክፍሎች ተመሳሳይ ፊደል ያላቸው ነገር ግን ዘርፋቸው የተለያየ (ተፈጥሮ/ማህበራዊ) ክፍሎች ተፈቅዷሉ።',
  }
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() =>
    localStorage.getItem('arerti_lang') || 'en'
  )

  const toggleLang = useCallback(() => {
    setLang(l => {
      const next = l === 'en' ? 'am' : 'en'
      localStorage.setItem('arerti_lang', next)
      return next
    })
  }, [])

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key
  }, [lang])

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t, isAmharic: lang === 'am' }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used inside <LanguageProvider>')
  return ctx
}
