import { useEffect, useState } from 'react'
import { studentService } from '../services/studentService'
import { classService } from '../services/classService'
import { registrationService } from '../services/registrationService'
import { useLanguage } from '../context/LanguageContext'
import Modal from '../components/Modal'
import StudentEnrollmentWizard from '../components/StudentEnrollmentWizard'
import toast from 'react-hot-toast'

const EMPTY = {
    email: '', fullName: '', phone: '',
    dateOfBirth: '', gender: '', parentName: '', parentPhone: '',
    enrollmentYear: new Date().getFullYear(), sectionId: ''
}

function CredentialsModal({ student, onClose }) {
    const { t } = useLanguage()
    const [copied, setCopied] = useState(false)
    const text = `Student: ${student.fullName}\nUsername: ${student.generatedUsername}\nPassword: ${student.generatedPassword}\nLogin at: ${window.location.origin}`
    const handleCopy = () => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000) }

    return (
        <div className="space-y-4">
            <div className="rounded-lg bg-green-50 border border-green-200 p-3 text-sm text-green-800">
                ✅ {t('studentRegisteredSuccess')}
            </div>
            <div className="rounded-lg bg-slate-100 p-4 font-mono text-sm space-y-1">
                <p><span className="text-slate-500">{t('student')}:</span> <strong>{student.fullName}</strong></p>
                <p><span className="text-slate-500">UID:</span> <strong>{student.studentUid}</strong></p>
                <p><span className="text-slate-500">{t('username')}:</span> <strong>{student.generatedUsername}</strong></p>
                <p><span className="text-slate-500">{t('password')}:</span> <strong>{student.generatedPassword}</strong></p>
                <p><span className="text-slate-500">{t('email')}:</span> <strong>{student.email}</strong></p>
            </div>
            <p className="text-xs text-slate-500">⚠️ {t('passwordShownOnce')}</p>
            <div className="flex justify-end gap-2">
                <button className="btn-ghost" onClick={handleCopy}>{copied ? `✓ ${t('copied')}` : t('copyToClipboard')}</button>
                <button className="btn-primary" onClick={onClose}>{t('done')}</button>
            </div>
        </div>
    )
}

function StudentForm({ initial, sections, onSubmit, onClose, loading, isEdit }) {
    const { t } = useLanguage()
    const [form, setForm] = useState(initial)
    const set = (k, v) => setForm(f => ({ ...f, [k]: v }))

    const handleSubmit = (e) => {
        e.preventDefault()
        onSubmit({
            ...form,
            sectionId: form.sectionId ? Number(form.sectionId) : null,
            enrollmentYear: form.enrollmentYear ? Number(form.enrollmentYear) : null,
            dateOfBirth: form.dateOfBirth || null,
        })
    }

    return (
        <form onSubmit={handleSubmit} className="space-y-3">
            {!isEdit && (
                <div className="rounded-lg bg-blue-50 border border-blue-200 p-3 text-xs text-blue-700">
                    ℹ️ {t('credentialsAutoGenerated')}
                </div>
            )}
            <div className="grid grid-cols-2 gap-3">
                <div>
                    <label className="field-label">{t('fullName')} *</label>
                    <input className="field" value={form.fullName} onChange={e => set('fullName', e.target.value)} required />
                </div>
                <div>
                    <label className="field-label">{t('email')} *</label>
                    <input className="field" type="email" value={form.email} onChange={e => set('email', e.target.value)} required />
                </div>
                <div>
                    <label className="field-label">{t('phone')}</label>
                    <input className="field" value={form.phone} onChange={e => set('phone', e.target.value)} />
                </div>
                <div>
                    <label className="field-label">{t('gender')}</label>
                    <select className="field" value={form.gender} onChange={e => set('gender', e.target.value)}>
                        <option value="">—</option>
                        <option value="Male">{t('male')}</option>
                        <option value="Female">{t('female')}</option>
                    </select>
                </div>
                <div>
                    <label className="field-label">{t('dateOfBirth')}</label>
                    <input className="field" type="date" value={form.dateOfBirth} onChange={e => set('dateOfBirth', e.target.value)} />
                </div>
                <div>
                    <label className="field-label">{t('enrollmentYear')}</label>
                    <input className="field" type="number" value={form.enrollmentYear} onChange={e => set('enrollmentYear', e.target.value)} />
                </div>
                <div>
                    <label className="field-label">{t('parentName')} *</label>
                    <input className="field" value={form.parentName} onChange={e => set('parentName', e.target.value)} required />
                </div>
                <div>
                    <label className="field-label">{t('guardianPhone')}</label>
                    <input className="field" value={form.parentPhone} onChange={e => set('parentPhone', e.target.value)} />
                </div>
            </div>
            <div>
                <label className="field-label">{t('classSection')}</label>
                <select className="field" value={form.sectionId} onChange={e => set('sectionId', e.target.value)}>
                    <option value="">— {t('unassigned')} —</option>
                    {sections.map(s => (
                        <option key={s.id} value={s.id}>{t('grade')} {s.grade} – {s.section} ({s.academicYear})</option>
                    ))}
                </select>
            </div>
            <div className="flex justify-end gap-2 pt-2">
                <button type="button" className="btn-ghost" onClick={onClose}>{t('cancel')}</button>
                <button type="submit" className="btn-primary" disabled={loading}>
                    {loading ? t('saving') : t('save')}
                </button>
            </div>
        </form>
    )
}

// ── Student detail modal (shows ALL info including photo & documents) ─────────
function StudentDetailModal({ student, sections, onClose, onEdit }) {
    const { t } = useLanguage()
    const section = sections.find(s => s.id === student.sectionId)

    const infoFields = [
        ['UID',              student.studentUid],
        [t('fullName'),      student.fullName],
        [t('email'),         student.email],
        [t('username'),      student.username],
        [t('phone'),         student.phone],
        [t('gender'),        student.gender ? t(student.gender.toLowerCase()) || student.gender : '—'],
        [t('dateOfBirth'),   student.dateOfBirth || '—'],
        [t('enrollmentYear'),student.enrollmentYear || '—'],
        [t('classSection'),  section ? `${t('grade')} ${section.grade} – ${section.section} (${section.academicYear})` : t('unassigned')],
        [t('parentName'),    student.parentName || '—'],
        [t('guardianPhone'), student.parentPhone || '—'],
    ]

    return (
        <div className="space-y-5">
            {/* Photo + name header */}
            <div className="flex items-center gap-4">
                {student.photoUrl ? (
                    <img
                        src={student.photoUrl}
                        alt={student.fullName}
                        className="w-20 h-20 rounded-full object-cover border-2 border-slate-200 shrink-0"
                        onError={e => { e.currentTarget.style.display = 'none' }}
                    />
                ) : (
                    <div className="w-20 h-20 rounded-full bg-brand/20 flex items-center justify-center text-brand font-bold text-3xl shrink-0">
                        {student.fullName?.charAt(0)}
                    </div>
                )}
                <div>
                    <div className="font-semibold text-slate-900 text-lg">{student.fullName}</div>
                    <div className="text-xs text-slate-400 font-mono">{student.studentUid}</div>
                    {student.sectionLabel && (
                        <div className="text-xs text-brand mt-0.5">{student.sectionLabel}</div>
                    )}
                </div>
            </div>

            {/* Info fields */}
            <dl className="divide-y divide-slate-100">
                {infoFields.map(([label, value]) => (
                    <div key={label} className="flex justify-between py-2 text-sm">
                        <dt className="text-slate-500 shrink-0 mr-4">{label}</dt>
                        <dd className="font-medium text-slate-900 text-right break-all">{value || '—'}</dd>
                    </div>
                ))}
            </dl>

            {/* Documents */}
            {student.photoUrl && (
                <div className="pt-1 border-t border-slate-100">
                    <p className="text-xs uppercase tracking-wide text-slate-400 mb-2">{t('documentsSection')}</p>
                    <div className="flex gap-3 flex-wrap">
                        <a href={student.photoUrl} target="_blank" rel="noreferrer"
                            className="flex items-center gap-1.5 text-xs text-brand hover:underline bg-brand/5 px-3 py-1.5 rounded-lg">
                            📷 {t('studentPhoto')}
                        </a>
                    </div>
                </div>
            )}

            <div className="flex justify-end gap-2 pt-2">
                <button className="btn-ghost" onClick={onClose}>{t('close')}</button>
                <button className="btn-primary" onClick={onEdit}>{t('edit')}</button>
            </div>
        </div>
    )
}

export default function StudentsPage() {
    const [students, setStudents] = useState([])
    const [sections, setSections] = useState([])
    const [loading, setLoading] = useState(true)
    const [saving, setSaving] = useState(false)
    const [modal, setModal] = useState(null)   // { mode: 'add'|'edit'|'detail'|'enroll', student? }
    const [credentialsModal, setCredentialsModal] = useState(null)
    const [enrollModal, setEnrollModal] = useState(false)   // full wizard
    const [activeWindow, setActiveWindow] = useState(null)  // active registration window or null
    const [search, setSearch] = useState('')
    const [confirmDelete, setConfirmDelete] = useState(null)
    const { t } = useLanguage()

    const load = async () => {
        setLoading(true)
        try {
            const [s, c, windows] = await Promise.all([
                studentService.getAll(),
                classService.getAll(),
                registrationService.getWindows().catch(() => []),
            ])
            setStudents(s)
            setSections(c)
            const open = windows.find(w => w.status === 'OPEN')
            setActiveWindow(open || null)
        } catch { toast.error(t('failedToLoad')) }
        finally { setLoading(false) }
    }

    useEffect(() => { load() }, [])

    const handleSave = async (payload) => {
        setSaving(true)
        try {
            await studentService.update(modal.student.id, payload)
            toast.success(t('studentUpdated'))
            setModal(null)
            load()
        } catch (err) {
            toast.error(err.response?.data?.message || t('saveFailed'))
        } finally { setSaving(false) }
    }

    const handleDelete = async (id) => {
        try {
            await studentService.remove(id)
            toast.success(t('studentDeleted'))
            setConfirmDelete(null); load()
        } catch { toast.error(t('deleteFailed')) }
    }

    const filtered = students.filter(s =>
        s.fullName?.toLowerCase().includes(search.toLowerCase()) ||
        s.studentUid?.toLowerCase().includes(search.toLowerCase()) ||
        s.email?.toLowerCase().includes(search.toLowerCase())
    )

    return (
        <div>
            <div className="flex items-center justify-between mb-6">
                <div>
                    <h1 className="font-display text-2xl font-bold text-slate-900">{t('studentsPage')}</h1>
                    <p className="text-slate-500 mt-1">{students.length} {t('enrolled')}</p>
                </div>
            </div>

            <div className="mb-4">
                <input className="field max-w-sm" placeholder={`${t('search')}…`}
                    value={search} onChange={e => setSearch(e.target.value)} />
            </div>

            <div className="card overflow-x-auto p-0">
                {loading ? (
                    <div className="p-8 text-center text-slate-500">{t('loading')}</div>
                ) : filtered.length === 0 ? (
                    <div className="p-8 text-center text-slate-500">{t('noStudentsFound')}</div>
                ) : (
                    <table className="w-full text-sm">
                        <thead>
                            <tr className="border-b border-slate-200 bg-slate-50 text-left text-xs uppercase text-slate-500 tracking-wide">
                                <th className="px-4 py-3">UID</th>
                                <th className="px-4 py-3">{t('fullName')}</th>
                                <th className="px-4 py-3">{t('email')}</th>
                                <th className="px-4 py-3">{t('username')}</th>
                                <th className="px-4 py-3">{t('gender')}</th>
                                <th className="px-4 py-3">{t('dateOfBirth')}</th>
                                <th className="px-4 py-3">{t('classSection')}</th>
                                <th className="px-4 py-3">{t('parentName')}</th>
                                <th className="px-4 py-3">{t('guardianPhone')}</th>
                                <th className="px-4 py-3">{t('enrollmentYear')}</th>
                                <th className="px-4 py-3 text-right">{t('actions')}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {filtered.map(s => (
                                <tr key={s.id} className="border-b border-slate-100 hover:bg-slate-50 transition cursor-pointer"
                                    onClick={() => setModal({ mode: 'detail', student: s })}>
                                    <td className="px-4 py-3 font-mono text-brand text-xs">{s.studentUid}</td>
                                    <td className="px-4 py-3 font-medium text-slate-900">{s.fullName}</td>
                                    <td className="px-4 py-3 text-slate-600 text-xs">{s.email}</td>
                                    <td className="px-4 py-3 font-mono text-xs text-slate-500">{s.username}</td>
                                    <td className="px-4 py-3 text-slate-600">{s.gender ? t(s.gender.toLowerCase()) || s.gender : '—'}</td>
                                    <td className="px-4 py-3 text-slate-600 text-xs">{s.dateOfBirth || '—'}</td>
                                    <td className="px-4 py-3 text-slate-600">{s.sectionLabel || '—'}</td>
                                    <td className="px-4 py-3 text-slate-600">{s.parentName || '—'}</td>
                                    <td className="px-4 py-3 text-slate-600 text-xs">{s.parentPhone || '—'}</td>
                                    <td className="px-4 py-3 text-slate-600">{s.enrollmentYear || '—'}</td>
                                    <td className="px-4 py-3 text-right space-x-2" onClick={e => e.stopPropagation()}>
                                        <button className="text-xs text-brand hover:underline"
                                            onClick={() => setModal({ mode: 'edit', student: s })}>{t('edit')}</button>
                                        <button className="text-xs text-red-500 hover:underline"
                                            onClick={() => setConfirmDelete(s)}>{t('delete')}</button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                )}
            </div>

            {/* Detail modal */}
            {modal?.mode === 'detail' && (
                <Modal title={t('studentDetails')} onClose={() => setModal(null)}>
                    <StudentDetailModal
                        student={modal.student}
                        sections={sections}
                        onClose={() => setModal(null)}
                        onEdit={() => setModal({ mode: 'edit', student: modal.student })}
                    />
                </Modal>
            )}

            {/* Edit modal (simple form for quick edits) */}
            {modal?.mode === 'edit' && (
                <Modal title={t('editStudent')} onClose={() => setModal(null)}>
                    <StudentForm
                        initial={{
                            email: modal.student.email, fullName: modal.student.fullName,
                            phone: modal.student.phone || '', dateOfBirth: modal.student.dateOfBirth || '',
                            gender: modal.student.gender || '', parentName: modal.student.parentName || '',
                            parentPhone: modal.student.parentPhone || '',
                            enrollmentYear: modal.student.enrollmentYear || new Date().getFullYear(),
                            sectionId: modal.student.sectionId || '',
                        }}
                        sections={sections} onSubmit={handleSave}
                        onClose={() => setModal(null)} loading={saving} isEdit={true}
                    />
                </Modal>
            )}

            {/* Credentials modal */}
            {credentialsModal && (
                <Modal title={t('studentCredentials')} onClose={() => setCredentialsModal(null)}>
                    <CredentialsModal student={credentialsModal} onClose={() => setCredentialsModal(null)} />
                </Modal>
            )}

            {/* Delete confirm */}
            {confirmDelete && (
                <Modal title={t('confirmDelete')} onClose={() => setConfirmDelete(null)}>
                    <p className="text-slate-700">
                        {t('deleteStudentConfirm')} <strong>{confirmDelete.fullName}</strong> ({confirmDelete.studentUid})?
                    </p>
                    <div className="flex justify-end gap-2 mt-4">
                        <button className="btn-ghost" onClick={() => setConfirmDelete(null)}>{t('cancel')}</button>
                        <button className="btn-danger" onClick={() => handleDelete(confirmDelete.id)}>{t('delete')}</button>
                    </div>
                </Modal>
            )}

            {/* Full enrollment wizard modal */}
            {enrollModal && activeWindow && (
                <Modal title={`${t('addStudent')} — ${activeWindow.academicYear}`} onClose={() => setEnrollModal(false)} size="lg">
                    <StudentEnrollmentWizard
                        windowData={activeWindow}
                        onSuccess={() => { load() }}
                        onClose={() => setEnrollModal(false)}
                    />
                </Modal>
            )}
        </div>
    )
}
