import { useEffect, useState } from 'react'
import { studentService } from '../services/studentService'
import { classService } from '../services/classService'
import { useLanguage } from '../context/LanguageContext'
import Modal from '../components/Modal'
import toast from 'react-hot-toast'

const EMPTY = {
    email: '', fullName: '', phone: '',
    dateOfBirth: '', gender: '', parentName: '', parentPhone: '',
    enrollmentYear: new Date().getFullYear(), sectionId: ''
}

// ── Credentials display after creation ────────────────────────────────────────
function CredentialsModal({ student, onClose }) {
    const [copied, setCopied] = useState(false)

    const text = `Student: ${student.fullName}
Username: ${student.generatedUsername}
Password: ${student.generatedPassword}
Login at: ${window.location.origin}`

    const handleCopy = () => {
        navigator.clipboard.writeText(text)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    return (
        <div className="space-y-4">
            <div className="rounded-lg bg-green-50 border border-green-200 p-3 text-sm text-green-800">
                ✅ Student registered successfully. Share these credentials with the student.
            </div>
            <div className="rounded-lg bg-slate-100 p-4 font-mono text-sm space-y-1">
                <p><span className="text-slate-500">Student:</span> <strong>{student.fullName}</strong></p>
                <p><span className="text-slate-500">Student UID:</span> <strong>{student.studentUid}</strong></p>
                <p><span className="text-slate-500">Username:</span> <strong>{student.generatedUsername}</strong></p>
                <p><span className="text-slate-500">Password:</span> <strong>{student.generatedPassword}</strong></p>
                <p><span className="text-slate-500">Email:</span> <strong>{student.email}</strong></p>
            </div>
            <p className="text-xs text-slate-500">
                ⚠️ This password is shown only once. The student must change it on first login.
            </p>
            <div className="flex justify-end gap-2">
                <button className="btn-ghost" onClick={handleCopy}>
                    {copied ? '✓ Copied!' : 'Copy to Clipboard'}
                </button>
                <button className="btn-primary" onClick={onClose}>Done</button>
            </div>
        </div>
    )
}

// ── Student form ───────────────────────────────────────────────────────────────
function StudentForm({ initial, sections, onSubmit, onClose, loading, isEdit }) {
    const [form, setForm] = useState(initial)
    const set = (k, v) => setForm(f => ({ ...f, [k]: v }))

    const handleSubmit = (e) => {
        e.preventDefault()
        const payload = {
            ...form,
            sectionId: form.sectionId ? Number(form.sectionId) : null,
            enrollmentYear: form.enrollmentYear ? Number(form.enrollmentYear) : null,
            dateOfBirth: form.dateOfBirth || null,
        }
        onSubmit(payload)
    }

    return (
        <form onSubmit={handleSubmit} className="space-y-3">
            {!isEdit && (
                <div className="rounded-lg bg-blue-50 border border-blue-200 p-3 text-xs text-blue-700">
                    ℹ️ Username and password will be auto-generated by the system and shown to you after saving.
                </div>
            )}
            <div className="grid grid-cols-2 gap-3">
                <div>
                    <label className="field-label">Full Name *</label>
                    <input className="field" value={form.fullName} onChange={e => set('fullName', e.target.value)} required />
                </div>
                <div>
                    <label className="field-label">Email *</label>
                    <input className="field" type="email" value={form.email} onChange={e => set('email', e.target.value)} required />
                </div>
                <div>
                    <label className="field-label">Phone</label>
                    <input className="field" value={form.phone} onChange={e => set('phone', e.target.value)} />
                </div>
                <div>
                    <label className="field-label">Gender</label>
                    <select className="field" value={form.gender} onChange={e => set('gender', e.target.value)}>
                        <option value="">—</option>
                        <option>Male</option>
                        <option>Female</option>
                    </select>
                </div>
                <div>
                    <label className="field-label">Date of Birth</label>
                    <input className="field" type="date" value={form.dateOfBirth}
                        onChange={e => set('dateOfBirth', e.target.value)} />
                </div>
                <div>
                    <label className="field-label">Enrollment Year</label>
                    <input className="field" type="number" value={form.enrollmentYear}
                        onChange={e => set('enrollmentYear', e.target.value)} />
                </div>
                <div>
                    <label className="field-label">Parent Name *</label>
                    <input className="field" value={form.parentName} onChange={e => set('parentName', e.target.value)} required />
                </div>
                <div>
                    <label className="field-label">Parent Phone</label>
                    <input className="field" value={form.parentPhone} onChange={e => set('parentPhone', e.target.value)} />
                </div>
            </div>
            <div>
                <label className="field-label">Class / Section</label>
                <select className="field" value={form.sectionId} onChange={e => set('sectionId', e.target.value)}>
                    <option value="">— Unassigned —</option>
                    {sections.map(s => (
                        <option key={s.id} value={s.id}>
                            Grade {s.grade} – {s.section} ({s.academicYear})
                        </option>
                    ))}
                </select>
            </div>
            <div className="flex justify-end gap-2 pt-2">
                <button type="button" className="btn-ghost" onClick={onClose}>Cancel</button>
                <button type="submit" className="btn-primary" disabled={loading}>
                    {loading ? 'Saving…' : 'Save'}
                </button>
            </div>
        </form>
    )
}

// ── Main StudentsPage ──────────────────────────────────────────────────────────
export default function StudentsPage() {
    const [students, setStudents] = useState([])
    const [sections, setSections] = useState([])
    const [loading, setLoading] = useState(true)
    const [saving, setSaving] = useState(false)
    const [modal, setModal] = useState(null)
    const [credentialsModal, setCredentialsModal] = useState(null)
    const [search, setSearch] = useState('')
    const [confirmDelete, setConfirmDelete] = useState(null)
    const { t } = useLanguage()

    const load = async () => {
        setLoading(true)
        try {
            const [s, c] = await Promise.all([studentService.getAll(), classService.getAll()])
            setStudents(s)
            setSections(c)
        } catch {
            toast.error('Failed to load students')
        } finally {
            setLoading(false)
        }
    }

    useEffect(() => { load() }, [])

    const handleSave = async (payload) => {
        setSaving(true)
        try {
            if (modal.mode === 'add') {
                const newStudent = await studentService.create(payload)
                toast.success('Student registered')
                setModal(null)
                // Show credentials modal only on creation
                if (newStudent.generatedUsername) {
                    setCredentialsModal(newStudent)
                }
            } else {
                await studentService.update(modal.student.id, payload)
                toast.success('Student updated')
                setModal(null)
            }
            load()
        } catch (err) {
            toast.error(err.response?.data?.message || 'Save failed')
        } finally {
            setSaving(false)
        }
    }

    const handleDelete = async (id) => {
        try {
            await studentService.remove(id)
            toast.success('Student deleted')
            setConfirmDelete(null)
            load()
        } catch {
            toast.error('Delete failed')
        }
    }

    const filtered = students.filter(s =>
        s.fullName.toLowerCase().includes(search.toLowerCase()) ||
        s.studentUid.toLowerCase().includes(search.toLowerCase()) ||
        s.email.toLowerCase().includes(search.toLowerCase())
    )

    return (
        <div>
            <div className="flex items-center justify-between mb-6">
                <div>
                    <h1 className="font-display text-2xl font-bold text-slate-900">{t('studentsPage')}</h1>
                    <p className="text-slate-500 mt-1">{students.length} {t('enrolled')}</p>
                </div>
                <button className="btn-primary" onClick={() => setModal({ mode: 'add' })}>
                    + {t('addStudent')}
                </button>
            </div>

            <div className="mb-4">
                <input
                    className="field max-w-sm"
                    placeholder="Search by name, UID or email…"
                    value={search}
                    onChange={e => setSearch(e.target.value)}
                />
            </div>

            <div className="card overflow-x-auto p-0">
                {loading ? (
                    <div className="p-8 text-center text-slate-500">Loading…</div>
                ) : filtered.length === 0 ? (
                    <div className="p-8 text-center text-slate-500">No students found.</div>
                ) : (
                    <table className="w-full text-sm">
                        <thead>
                            <tr className="border-b border-slate-200 bg-slate-50 text-left text-xs uppercase text-slate-500 tracking-wide">
                                <th className="px-4 py-3">UID</th>
                                <th className="px-4 py-3">Name</th>
                                <th className="px-4 py-3">Email</th>
                                <th className="px-4 py-3">Username</th>
                                <th className="px-4 py-3">Gender</th>
                                <th className="px-4 py-3">Class</th>
                                <th className="px-4 py-3">Parent</th>
                                <th className="px-4 py-3 text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {filtered.map(s => (
                                <tr key={s.id} className="border-b border-slate-100 hover:bg-slate-50 transition">
                                    <td className="px-4 py-3 font-mono text-brand text-xs">{s.studentUid}</td>
                                    <td className="px-4 py-3 font-medium text-slate-900">{s.fullName}</td>
                                    <td className="px-4 py-3 text-slate-600">{s.email}</td>
                                    <td className="px-4 py-3 font-mono text-xs text-slate-500">{s.username}</td>
                                    <td className="px-4 py-3 text-slate-600">{s.gender || '—'}</td>
                                    <td className="px-4 py-3 text-slate-600">{s.sectionLabel || '—'}</td>
                                    <td className="px-4 py-3 text-slate-600">{s.parentName || '—'}</td>
                                    <td className="px-4 py-3 text-right space-x-2">
                                        <button
                                            className="text-xs text-brand hover:underline"
                                            onClick={() => setModal({ mode: 'edit', student: s })}
                                        >
                                            Edit
                                        </button>
                                        <button
                                            className="text-xs text-red-500 hover:underline"
                                            onClick={() => setConfirmDelete(s)}
                                        >
                                            Delete
                                        </button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                )}
            </div>

            {/* Add/Edit Modal */}
            {modal && (
                <Modal
                    title={modal.mode === 'add' ? 'Register Student' : 'Edit Student'}
                    onClose={() => setModal(null)}
                >
                    <StudentForm
                        initial={modal.mode === 'edit' ? {
                            email: modal.student.email,
                            fullName: modal.student.fullName,
                            phone: modal.student.phone || '',
                            dateOfBirth: modal.student.dateOfBirth || '',
                            gender: modal.student.gender || '',
                            parentName: modal.student.parentName || '',
                            parentPhone: modal.student.parentPhone || '',
                            enrollmentYear: modal.student.enrollmentYear || new Date().getFullYear(),
                            sectionId: modal.student.sectionId || '',
                        } : EMPTY}
                        sections={sections}
                        onSubmit={handleSave}
                        onClose={() => setModal(null)}
                        loading={saving}
                        isEdit={modal.mode === 'edit'}
                    />
                </Modal>
            )}

            {/* Generated credentials modal */}
            {credentialsModal && (
                <Modal title="Student Login Credentials" onClose={() => setCredentialsModal(null)}>
                    <CredentialsModal
                        student={credentialsModal}
                        onClose={() => setCredentialsModal(null)}
                    />
                </Modal>
            )}

            {/* Delete confirm */}
            {confirmDelete && (
                <Modal title="Confirm Delete" onClose={() => setConfirmDelete(null)}>
                    <p className="text-slate-700">
                        Delete student <strong>{confirmDelete.fullName}</strong> ({confirmDelete.studentUid})?
                        This will also remove their login account.
                    </p>
                    <div className="flex justify-end gap-2 mt-4">
                        <button className="btn-ghost" onClick={() => setConfirmDelete(null)}>Cancel</button>
                        <button className="btn-danger" onClick={() => handleDelete(confirmDelete.id)}>Delete</button>
                    </div>
                </Modal>
            )}
        </div>
    )
}
