package com.arerti.portal.dto;

import jakarta.validation.constraints.*;

import java.time.LocalDate;

/**
 * Used when admin creates a new student.
 * Username and password are AUTO-GENERATED by the system.
 * parentName (formerly guardianName) is required.
 */
public record StudentCreateRequest(
        @NotBlank @Email String email,
        @NotBlank String fullName,
        String phone,
        LocalDate dateOfBirth,
        String gender,
        @NotBlank String parentName,      // required — renamed from guardianName
        String parentPhone,
        Integer enrollmentYear,
        Long sectionId
) {}
