package com.arerti.portal.dto;

import jakarta.validation.constraints.*;

import java.time.LocalDate;

/** Admin creates a teacher — username/password auto-generated by system. */
public record TeacherCreateRequest(
        @NotBlank @Email String email,
        @NotBlank String fullName,
        String phone,
        String qualification,
        String specialization,
        LocalDate hireDate
) {}
